--This script aggregate by day the events from users, who installed our apps in last N days.  
--Step 1: Run and validate the query below in bigquery 
--Step 2: Create a daily schedule job(aka: schedule_job_A) to write the query result to table_A which contains results from all execution of the schedule job 
 --so their will be duplicate records in table A, the dedup script is in dedup.sql. Save the name of table_A for usage in dedup.sql 
CREATE TEMP FUNCTION
abstract_params(input_arr Array<struct<key string, value struct<string_value string, int_value int64, float_value float64, double_value float64>>>, key_value string,value_field int64)
RETURNS int64
LANGUAGE js AS r"""
 ret=0
 var i=input_arr.length;
 while(i--){
     if (input_arr[i].key===key_value) {
         if (value_field === 1) {
             ret=input_arr[i].value.int_value;
             i=0;
         } else if (value_field === 2) {
             ret=input_arr[i].value.float_value;
             i=0
         } else {
             ret=input_arr[i].value.double_value;
             i=0
         }
     }
 }
 return ret;
""";
with event_window as ( 
select current_date() as event_date union all 
select date_sub(current_date(), interval 1 day) union all 
select date_sub(current_date(), interval 2 day) union all 
select date_sub(current_date(), interval 3 day) union all 
select date_sub(current_date(), interval 4 day) union all 
select date_sub(current_date(), interval 5 day) union all 
select date_sub(current_date(), interval 6 day) union all 
select date_sub(current_date(), interval 7 day) union all 
select date_sub(current_date(), interval 8 day) union all 
select date_sub(current_date(), interval 9 day) union all 
select date_sub(current_date(), interval 10 day) union all 
select date_sub(current_date(), interval 11 day) union all 
select date_sub(current_date(), interval 12 day) union all 
select date_sub(current_date(), interval 13 day) union all 
select date_sub(current_date(), interval 14 day) union all 
select date_sub(current_date(), interval 15 day) union all 
select date_sub(current_date(), interval 16 day) union all 
select date_sub(current_date(), interval 17 day) union all 
select date_sub(current_date(), interval 18 day) union all 
select date_sub(current_date(), interval 19 day) union all 
select date_sub(current_date(), interval 20 day) union all 
select date_sub(current_date(), interval 21 day) union all 
select date_sub(current_date(), interval 22 day) union all 
select date_sub(current_date(), interval 23 day) union all 
select date_sub(current_date(), interval 24 day) union all 
select date_sub(current_date(), interval 25 day) union all 
select date_sub(current_date(), interval 26 day) union all 
select date_sub(current_date(), interval 27 day) union all 
select date_sub(current_date(), interval 28 day) union all 
select date_sub(current_date(), interval 29 day) union all 
select date_sub(current_date(), interval 30 day) union all 
select date_sub(current_date(), interval 31 day) union all 
select date_sub(current_date(), interval 32 day) union all 
select date_sub(current_date(), interval 33 day) union all 
select date_sub(current_date(), interval 34 day) union all 
select date_sub(current_date(), interval 35 day) union all 
select date_sub(current_date(), interval 36 day) union all 
select date_sub(current_date(), interval 37 day) union all 
select date_sub(current_date(), interval 38 day) union all 
select date_sub(current_date(), interval 39 day) union all 
select date_sub(current_date(), interval 40 day) union all 
select date_sub(current_date(), interval 41 day) union all 
select date_sub(current_date(), interval 42 day) union all 
select date_sub(current_date(), interval 43 day) union all 
select date_sub(current_date(), interval 44 day) union all 
select date_sub(current_date(), interval 45 day) union all 
select date_sub(current_date(), interval 46 day) union all 
select date_sub(current_date(), interval 47 day) union all 
select date_sub(current_date(), interval 48 day) union all 
select date_sub(current_date(), interval 49 day) union all 
select date_sub(current_date(), interval 50 day) union all 
select date_sub(current_date(), interval 51 day) union all 
select date_sub(current_date(), interval 52 day) union all 
select date_sub(current_date(), interval 53 day) union all 
select date_sub(current_date(), interval 54 day) union all 
select date_sub(current_date(), interval 55 day) union all 
select date_sub(current_date(), interval 56 day) union all 
select date_sub(current_date(), interval 57 day) union all 
select date_sub(current_date(), interval 58 day) union all 
select date_sub(current_date(), interval 59 day) union all 
select date_sub(current_date(), interval 60 day) 
), 
distinct_user_install_event as ( 
select 
user_pseudo_id as universal_user_id, 
date(event_date)  as install_date, 
count(0) 
from `state-of-survival.gcp_ss.custom_events` 
where date(event_date)  >= date_sub(current_date(), interval 60 day) 
and event_name= 'first_open' 
group by 1,2), 
distinct_user_install_event_with_next as ( 
select 
universal_user_id,install_date, 
ifnull(lag(install_date) over (partition by universal_user_id order by install_date desc),date('9999-12-31')) as next_install_date, 
from distinct_user_install_event
), 
full_user_date as ( 
select 
a.universal_user_id, 
a.install_date, 
b.event_date 
from distinct_user_install_event_with_next a 
cross join event_window b 
where b.event_date >= a.install_date 
and b.event_date < a.next_install_date 
order by universal_user_id, event_date 
), 
data_flat_1 as ( 
select 
user_pseudo_id as universal_user_id, 
event_name, 
date(event_date)  as event_date, 
if (event_name in ('session_start','first_open'), 1 , 0) as login_flag, 
 if (event_name in ('event_SS_Revenue') , 1 , 0) as pay_flag, 
if (event_name='login_music_state',1,0) as login_music_state__flag,
if (event_name='track_auth',1,0) as track_auth__count,
if (event_name='wd_daryl_unlock_new_buildings',1,0) as wd_daryl_unlock_new_buildings__count,
if (event_name='intel_v2',1,0) as intel_v2__count,
if (event_name='daily_reward',1,0) as daily_reward__count,
if (event_name='gold_event',1,0) as gold_event__count,
if (event_name='se_battle',1,0) as se_battle__count,
if (event_name='gather',1,0) as gather__count,
if (event_name='custom_iap',1,0) as custom_iap__count,
if (event_name='login_lord_gem',1,0) as login_lord_gem__count,
if (event_name='month_card',1,0) as month_card__count,
if (event_name='building_upgrade',1,0) as building_upgrade__count,
if (event_name='CMS',1,0) as CMS__count,
if (event_name='Halloween_Candy',1,0) as Halloween_Candy__count,
if (event_name='lord_gem_verification_not_received',1,0) as lord_gem_verification_not_received__count,
if (event_name='alliance_craft',1,0) as alliance_craft__count,
if (event_name='score_special',1,0) as score_special__count,
if (event_name='scout',1,0) as scout__count,
if (event_name='teleport',1,0) as teleport__count,
if (event_name='recharge_rebate',1,0) as recharge_rebate__count,
if (event_name='gameLike',1,0) as gameLike__count,
if (event_name='advance_research_upgrade',1,0) as advance_research_upgrade__count,
if (event_name='festival_daily_task',1,0) as festival_daily_task__count,
if (event_name='change_equipment',1,0) as change_equipment__count,
if (event_name='ab_test',1,0) as ab_test__count,
if (event_name='kingdom_war_pve',1,0) as kingdom_war_pve__count,
if (event_name='wd_user_get_quest_reward',1,0) as wd_user_get_quest_reward__count,
if (event_name='activity_festival_seven_days',1,0) as activity_festival_seven_days__count,
if (event_name='iap_charge_continuous',1,0) as iap_charge_continuous__count,
if (event_name='activity_plasma_scientific_prepare',1,0) as activity_plasma_scientific_prepare__count,
if (event_name='questionnaire',1,0) as questionnaire__count,
if (event_name='zombie_boss',1,0) as zombie_boss__count,
if (event_name='remote_config',1,0) as remote_config__count,
if (event_name='alliance_shop',1,0) as alliance_shop__count,
if (event_name='Stroy_Collect_Complete',1,0) as Stroy_Collect_Complete__flag,
if (event_name='today_first_login',1,0) as today_first_login__count,
if (event_name='activity_wd_seek',1,0) as activity_wd_seek__count,
if (event_name='honor_pass_2',1,0) as honor_pass_2__count,
if (event_name='train_troop_finish',1,0) as train_troop_finish__count,
if (event_name='live_streaming',1,0) as live_streaming__count,
if (event_name='timer_chest_gain',1,0) as timer_chest_gain__count,
if (event_name='gold_event_season',1,0) as gold_event_season__count,
if (event_name='building_upgrade_finish',1,0) as building_upgrade_finish__count,
if (event_name='quest_complete',1,0) as quest_complete__count,
if (event_name='chapter_quest_complete',1,0) as chapter_quest_complete__count,
if (event_name='upgrade_clue',1,0) as upgrade_clue__count,
if (event_name='dialog',1,0) as dialog__count,
if (event_name='leave_alliance',1,0) as leave_alliance__count,
if (event_name='survivor_support',1,0) as survivor_support__count,
if (event_name='lord_level_up',1,0) as lord_level_up__count,
if (event_name='localization_signin',1,0) as localization_signin__count,
if (event_name='analysis_center_war',1,0) as analysis_center_war__count,
if (event_name='go_back_claim_login_reward',1,0) as go_back_claim_login_reward__count,
if (event_name='go_back_claim_free_iap',1,0) as go_back_claim_free_iap__count,
if (event_name='halloween_event',1,0) as halloween_event__count,
if (event_name='battle',1,0) as battle__count,
if (event_name='disband_alliance',1,0) as disband_alliance__count,
if (event_name='gain_reward',1,0) as gain_reward__count,
if (event_name='combat',1,0) as combat__count,
if (event_name='alliance_help',1,0) as alliance_help__count,
if (event_name='vip',1,0) as vip__count,
if (event_name='research_finish',1,0) as research_finish__count,
if (event_name='login_lord_equipment',1,0) as login_lord_equipment__count,
if (event_name='alliance_iap_gift',1,0) as alliance_iap_gift__count,
if (event_name='buff_change',1,0) as buff_change__count,
if (event_name='research_quest_complete',1,0) as research_quest_complete__count,
if (event_name='battle_gather',1,0) as battle_gather__count,
if (event_name='talent_skill',1,0) as talent_skill__count,
if (event_name='chapter_group_start',1,0) as chapter_group_start__count,
if (event_name='hidden_exploration',1,0) as hidden_exploration__count,
if (event_name='battle_monster',1,0) as battle_monster__count,
if (event_name='join_alliance',1,0) as join_alliance__count,
if (event_name='world_line',1,0) as world_line__count,
if (event_name='localization_exchange_event',1,0) as localization_exchange_event__count,
if (event_name='prosperity',1,0) as prosperity__count,
if (event_name='festival_region_pass',1,0) as festival_region_pass__count,
if (event_name='alliance_tech',1,0) as alliance_tech__count,
if (event_name='chapter_group_complete',1,0) as chapter_group_complete__count,
if (event_name='go_back_sprint_quest_complete',1,0) as go_back_sprint_quest_complete__count,
if (event_name='activity_advance_research_five_days',1,0) as activity_advance_research_five_days__count,
if (event_name='alliance_request',1,0) as alliance_request__count,
if (event_name='alliance_mark',1,0) as alliance_mark__count,
if (event_name='explore_loading',1,0) as explore_loading__count,
if (event_name='dress_up',1,0) as dress_up__count,
if (event_name='exchange_code',1,0) as exchange_code__count,
if (event_name='dismiss_troop',1,0) as dismiss_troop__count,
if (event_name='go_back',1,0) as go_back__count,
if (event_name='fresher_pease_shield',1,0) as fresher_pease_shield__count,
if (event_name='user_agreement',1,0) as user_agreement__count,
if (event_name='world_event_season_sign',1,0) as world_event_season_sign__count,
if (event_name='week_card',1,0) as week_card__count,
if (event_name='activity_survivor_seven_days',1,0) as activity_survivor_seven_days__count,
if (event_name='supplememt_tropps_base',1,0) as supplememt_tropps_base__count,
if (event_name='activity_red_packet',1,0) as activity_red_packet__count,
if (event_name='battle_power_change', abstract_params(event_params,'change_power',1) ,null) as battle_power_change__change_power,
if (event_name='wd_daryl_get_reward',1,0) as wd_daryl_get_reward__count,
if (event_name='avaleague_quest',1,0) as avaleague_quest__count,
if (event_name='city_buff',1,0) as city_buff__count,
if (event_name='big_timer_chest',1,0) as big_timer_chest__count,
if (event_name='survivor_unlock',1,0) as survivor_unlock__count,
if (event_name='custom_iap_2',1,0) as custom_iap_2__count,
if (event_name='hero_drop',1,0) as hero_drop__count,
if (event_name='tutorial_ex',1,0) as tutorial_ex__count,
if (event_name='unlock_city_block_v3',1,0) as unlock_city_block_v3__count,
if (event_name='exchange_survivor_chip',1,0) as exchange_survivor_chip__count,
if (event_name='kingdom_war',1,0) as kingdom_war__count,
if (event_name='plasma_building_prepare',1,0) as plasma_building_prepare__count,
if (event_name='gameStoreScore',1,0) as gameStoreScore__count,
if (event_name='growth_fund',1,0) as growth_fund__count,
if (event_name='kvk',1,0) as kvk__count,
if (event_name='wd_user_draw_real_reward',1,0) as wd_user_draw_real_reward__count,
if (event_name='kvk_recuperate',1,0) as kvk_recuperate__count,
if (event_name='heal_troop',1,0) as heal_troop__flag,
if (event_name='donate', abstract_params(event_params,'tot_times',1) ,null) as donate__tot_times,
if (event_name='ask_alliance_help',1,0) as ask_alliance_help__count,
if (event_name='view_other_city',1,0) as view_other_city__count,
if (event_name='alliance_boss',1,0) as alliance_boss__count,
if (event_name='survivor_search',1,0) as survivor_search__count,
if (event_name='reward_center',1,0) as reward_center__count,
if (event_name='alliance_donate_rank',1,0) as alliance_donate_rank__count,
if (event_name='survivor',1,0) as survivor__count,
if (event_name='user_vault',1,0) as user_vault__count,
if (event_name='poison_land',1,0) as poison_land__count,
if (event_name='battle_pvp_detail',1,0) as battle_pvp_detail__count,
if (event_name='seven_day',1,0) as seven_day__count,
if (event_name='chapter_quest_gain_quest_reward',1,0) as chapter_quest_gain_quest_reward__count,
if (event_name='zombie_invasion',1,0) as zombie_invasion__count,
if (event_name='exploration',1,0) as exploration__count,
if (event_name='lord_equipment_gem_power', abstract_params(event_params,'change_power',1) ,null) as lord_equipment_gem_power__change_power,
if (event_name='IapPaymentSuccess',1,0) as IapPaymentSuccess__count,
if (event_name='survivor_camp',1,0) as survivor_camp__count,
if (event_name='hide_troop', abstract_params(event_params,'hided_troops_power',1) ,null) as hide_troop__hided_troops_power,
if (event_name='europe_policy',1,0) as europe_policy__count,
if (event_name='micro_com',1,0) as micro_com__count,
if (event_name='activity_daily_iap_accumulative_reward',1,0) as activity_daily_iap_accumulative_reward__count,
if (event_name='powerup',1,0) as powerup__count,
if (event_name='roguelike',1,0) as roguelike__count,
if (event_name='claim_sprint_box_reward',1,0) as claim_sprint_box_reward__count,
if (event_name='go_back_new_world',1,0) as go_back_new_world__count,
if (event_name='unlock_city_block',1,0) as unlock_city_block__count,
if (event_name='supplememt_tropps',1,0) as supplememt_tropps__count,
if (event_name='loading',1,0) as loading__count,
if (event_name='city_decoration',1,0) as city_decoration__count,
if (event_name='stamina',1,0) as stamina__count,
if (event_name='big_turntable',1,0) as big_turntable__count,
if (event_name='wd_daryl_new_clue_gained',1,0) as wd_daryl_new_clue_gained__count,
if (event_name='train_troop',1,0) as train_troop__count,
if (event_name='story',1,0) as story__count,
if (event_name='research_upgrade',1,0) as research_upgrade__flag,
if (event_name='alliance_speedup',1,0) as alliance_speedup__count,
if (event_name='custom_iap_3',1,0) as custom_iap_3__count,
if (event_name='shop',1,0) as shop__count,
if (event_name='login',1,0) as login__count,
if (event_name='cheat_user',1,0) as cheat_user__flag,
if (event_name='kingdom_event',1,0) as kingdom_event__count,
if (event_name='world_event',1,0) as world_event__count,
if (event_name='quest_gain_reward',1,0) as quest_gain_reward__count,
if (event_name='payment_submit_order',1,0) as payment_submit_order__count,
if (event_name='chapter_quest_gain_group_reward',1,0) as chapter_quest_gain_group_reward__count,
if (event_name='survivor_will',1,0) as survivor_will__count,
if (event_name='forge_equipment',1,0) as forge_equipment__count,
if (event_name='alliance_zone',1,0) as alliance_zone__count,
if (event_name='survivor_summon',1,0) as survivor_summon__count,
if (event_name='city_fire',1,0) as city_fire__flag,
if (event_name='buy_month_card',1,0) as buy_month_card__count,
if (event_name='survivor_link',1,0) as survivor_link__count,
if (event_name='create_alliance',1,0) as create_alliance__count,
if (event_name='iap_exchange',1,0) as iap_exchange__count,
if (event_name='super_exchange',1,0) as super_exchange__count,
if (event_name='charge_first_pass',1,0) as charge_first_pass__count,
if (event_name='switch_kingdom',1,0) as switch_kingdom__count,
if (event_name='activity_gift',1,0) as activity_gift__count,
if (event_name='tutorial',1,0) as tutorial__count,
if (event_name='survivor_equipment',1,0) as survivor_equipment__count,
if (event_name='npc_store',1,0) as npc_store__count,
if (event_name='wd_user_answer_question',1,0) as wd_user_answer_question__count,
if (event_name='alliance_mobilization',1,0) as alliance_mobilization__count,
if (event_name='intelligence_stamina', abstract_params(event_params,'change',1) ,null) as intelligence_stamina__change,
if (event_name='dynamic_recommend_iap',1,0) as dynamic_recommend_iap__count,
if (event_name='upgrade_troop',1,0) as upgrade_troop__count,
if (event_name='MarchLine_Click',1,0) as MarchLine_Click__count,
if (event_name='login_survivor_equipment',1,0) as login_survivor_equipment__flag,
if (event_name='c',1,0) as c__count,
if (event_name='fallen_knight',1,0) as fallen_knight__count,
if (event_name='fallen_knight_defend_success',1,0) as fallen_knight_defend_success__count,
if (event_name='battle_gve',1,0) as battle_gve__count,
if (event_name='user_gem',1,0) as user_gem__count,
if (event_name='puzzle_pve',1,0) as puzzle_pve__count,
if (event_name='lord_equipment_power',1,0) as lord_equipment_power__count,
if (event_name='hunter_house',1,0) as hunter_house__count,
if (event_name='cultivate',1,0) as cultivate__count,
if (event_name='plasma_cannon',1,0) as plasma_cannon__count,
if (event_name='go_back_claim_sprint_quest_reward',1,0) as go_back_claim_sprint_quest_reward__count,
if (event_name='storyline',1,0) as storyline__count,
if (event_name='iap_trigger',1,0) as iap_trigger__count,
if (event_name='wounded_reward', abstract_params(event_params,'lost_power',1) ,null) as wounded_reward__lost_power,
if (event_name='advance_research_finish',1,0) as advance_research_finish__count,
if (event_name='go_back_user_info',1,0) as go_back_user_info__count,
if (event_name='festival_pass',1,0) as festival_pass__count,
if (event_name='wd_daryl_clue_compose',1,0) as wd_daryl_clue_compose__count,
if (event_name='payment_pay_type',1,0) as payment_pay_type__count,
if (event_name='user_skill',1,0) as user_skill__count,
if (event_name='walking_dead_event',1,0) as walking_dead_event__count,
if (event_name='mini_wonder_war',1,0) as mini_wonder_war__count,
if (event_name='faq1_0',1,0) as faq1_0__count,
if (event_name='buy_week_card',1,0) as buy_week_card__count,
if (event_name='stronghold_level_reward',1,0) as stronghold_level_reward__count,
if (event_name='world_event_memorial_book_abyss',1,0) as world_event_memorial_book_abyss__count,
if (event_name='festival_wish',1,0) as festival_wish__count,
if (event_name='festival_collection',1,0) as festival_collection__count,
if (event_name='focus_out',1,0) as focus_out__flag,
if (event_name='MonthCard',1,0) as MonthCard__count,
if (event_name='focus_in',1,0) as focus_in__flag,
if (event_name='activity_limit_time_discount_shop',1,0) as activity_limit_time_discount_shop__count,
if (event_name='micro_com1_1',1,0) as micro_com1_1__count,
if (event_name='go_back_claim_sprint_task_reward',1,0) as go_back_claim_sprint_task_reward__count,
if (event_name='march',1,0) as march__count,
if (event_name='transaction',1,0) as transaction__count,
if (event_name='festival_boss',1,0) as festival_boss__count,
if (event_name='wd_collection',1,0) as wd_collection__count,
if (event_name='avaleague',1,0) as avaleague__count,
if (event_name='avaleague_guess',1,0) as avaleague_guess__count,
if (event_name='exchange_gifts',1,0) as exchange_gifts__count,
if (event_name='auto_fix_date',1,0) as auto_fix_date__flag,
if (event_name='festival_navigation',1,0) as festival_navigation__count,
if (event_name='lord_gem_verification_attack_boss_finish',1,0) as lord_gem_verification_attack_boss_finish__count,
if (event_name='open_fallen_knight',1,0) as open_fallen_knight__count,
if (event_name='lord_gem_verification_quest_complete',1,0) as lord_gem_verification_quest_complete__count,
if (event_name='action',1,0) as action__count,
if (event_name='anti_addiction',1,0) as anti_addiction__count,
if (event_name='climbing_tower',1,0) as climbing_tower__count,
if (event_name='festival_story',1,0) as festival_story__count,
if (event_name='new_big_turntable',1,0) as new_big_turntable__count,
if (event_name='festival_zodiac_collect',1,0) as festival_zodiac_collect__count,
if (event_name='startDailyQuestBI',1,0) as startDailyQuestBI__count,
if (event_name='lord_gem_verification_attack_boss_start',1,0) as lord_gem_verification_attack_boss_start__count,
if (event_name='lord_gem_verification_combat_ready_receive',1,0) as lord_gem_verification_combat_ready_receive__count,
if (event_name='abyss',1,0) as abyss__count,
if (event_name='honor_pass',1,0) as honor_pass__count,
if (event_name='hero_flip_card_over',1,0) as hero_flip_card_over__count,
if (event_name='launch_start',1,0) as launch_start__flag,
if (event_name='lord_gem_verification_quest_receive',1,0) as lord_gem_verification_quest_receive__count,
if (event_name='activity_festival_equip_seven_days',1,0) as activity_festival_equip_seven_days__count,
if (event_name='lord_gem_verification_rank',1,0) as lord_gem_verification_rank__count,
if (event_name='world_open',1,0) as world_open__count,
if (event_name='season_climb_tower',1,0) as season_climb_tower__count,
if (event_name='treasure_discover',1,0) as treasure_discover__count,
if (event_name='noteBookWithoutAlliance',1,0) as noteBookWithoutAlliance__count,
if (event_name='throne_shock_relocation',1,0) as throne_shock_relocation__count,
if (event_name='lord_gem_verification_buff_change',1,0) as lord_gem_verification_buff_change__count,
if (event_name='friend_list_option',1,0) as friend_list_option__count,
if (event_name='festival_pass_2',1,0) as festival_pass_2__count,
if (event_name='submitDailyQuestBI',1,0) as submitDailyQuestBI__count,
if (event_name='exchange_event',1,0) as exchange_event__count,
if (event_name='invite_new_user',1,0) as invite_new_user__count,
if (event_name='start_gather_march',1,0) as start_gather_march__count,
if (event_name='activity_recycle',1,0) as activity_recycle__count,
if (event_name='achievement',1,0) as achievement__count,
if (event_name='session_start',1,0) as session_start__count,
if (event_name='dialog_skip',1,0) as dialog_skip__count,
if (event_name='lord_gem_verification_ready_open',1,0) as lord_gem_verification_ready_open__count,
if (event_name='lord_gem_verification_score_quest_complete',1,0) as lord_gem_verification_score_quest_complete__count,
if (event_name='world_event_memorial_book_kvk',1,0) as world_event_memorial_book_kvk__count,
if (event_name='equipment_signin',1,0) as equipment_signin__count,
if (event_name='daily_sign_in',1,0) as daily_sign_in__count,
if (event_name='ava',1,0) as ava__count,
if (event_name='session_en',1,0) as session_en__count,
if (event_name='super_exchange_2',1,0) as super_exchange_2__count,
if (event_name='wd_lottery',1,0) as wd_lottery__count,
if (event_name='service_monitoring',1,0) as service_monitoring__count,
if (event_name='alliance_trade',1,0) as alliance_trade__count,
if (event_name='activity_drop',1,0) as activity_drop__count,
if (event_name='session_end',1,0) as session_end__count,
if (event_name='lord_gem_verification_ready_score_change',1,0) as lord_gem_verification_ready_score_change__count,
if (event_name='event_SS_Revenue', abstract_params(event_params,'value_in_usd',3) ,null) as event_SS_Revenue__value_in_usd,
if (event_name='first_open',1,0) as first_open__flag
from `state-of-survival.gcp_ss.custom_events` 
where date(event_date)  >= date_sub(current_date(), interval 60 day) 
), 
event_agg_by_day as ( 
select 
universal_user_id,
event_date, 
if(sum(login_flag)=0, 0,1) as login_flag, 
if(sum(pay_flag)=0, 0, 1 ) as pay_flag, 
if(sum(case when event_name = 'login_music_state' then login_music_state__flag end)>0,1,0) as login_music_state__flag,
ifnull(sum(case when event_name = 'track_auth' then track_auth__count end),0) as track_auth__count,
ifnull(sum(case when event_name = 'wd_daryl_unlock_new_buildings' then wd_daryl_unlock_new_buildings__count end),0) as wd_daryl_unlock_new_buildings__count,
ifnull(sum(case when event_name = 'intel_v2' then intel_v2__count end),0) as intel_v2__count,
ifnull(sum(case when event_name = 'daily_reward' then daily_reward__count end),0) as daily_reward__count,
ifnull(sum(case when event_name = 'gold_event' then gold_event__count end),0) as gold_event__count,
ifnull(sum(case when event_name = 'se_battle' then se_battle__count end),0) as se_battle__count,
ifnull(sum(case when event_name = 'gather' then gather__count end),0) as gather__count,
ifnull(sum(case when event_name = 'custom_iap' then custom_iap__count end),0) as custom_iap__count,
ifnull(sum(case when event_name = 'login_lord_gem' then login_lord_gem__count end),0) as login_lord_gem__count,
ifnull(sum(case when event_name = 'month_card' then month_card__count end),0) as month_card__count,
ifnull(sum(case when event_name = 'building_upgrade' then building_upgrade__count end),0) as building_upgrade__count,
ifnull(sum(case when event_name = 'CMS' then CMS__count end),0) as CMS__count,
ifnull(sum(case when event_name = 'Halloween_Candy' then Halloween_Candy__count end),0) as Halloween_Candy__count,
ifnull(sum(case when event_name = 'lord_gem_verification_not_received' then lord_gem_verification_not_received__count end),0) as lord_gem_verification_not_received__count,
ifnull(sum(case when event_name = 'alliance_craft' then alliance_craft__count end),0) as alliance_craft__count,
ifnull(sum(case when event_name = 'score_special' then score_special__count end),0) as score_special__count,
ifnull(sum(case when event_name = 'scout' then scout__count end),0) as scout__count,
ifnull(sum(case when event_name = 'teleport' then teleport__count end),0) as teleport__count,
ifnull(sum(case when event_name = 'recharge_rebate' then recharge_rebate__count end),0) as recharge_rebate__count,
ifnull(sum(case when event_name = 'gameLike' then gameLike__count end),0) as gameLike__count,
ifnull(sum(case when event_name = 'advance_research_upgrade' then advance_research_upgrade__count end),0) as advance_research_upgrade__count,
ifnull(sum(case when event_name = 'festival_daily_task' then festival_daily_task__count end),0) as festival_daily_task__count,
ifnull(sum(case when event_name = 'change_equipment' then change_equipment__count end),0) as change_equipment__count,
ifnull(sum(case when event_name = 'ab_test' then ab_test__count end),0) as ab_test__count,
ifnull(sum(case when event_name = 'kingdom_war_pve' then kingdom_war_pve__count end),0) as kingdom_war_pve__count,
ifnull(sum(case when event_name = 'wd_user_get_quest_reward' then wd_user_get_quest_reward__count end),0) as wd_user_get_quest_reward__count,
ifnull(sum(case when event_name = 'activity_festival_seven_days' then activity_festival_seven_days__count end),0) as activity_festival_seven_days__count,
ifnull(sum(case when event_name = 'iap_charge_continuous' then iap_charge_continuous__count end),0) as iap_charge_continuous__count,
ifnull(sum(case when event_name = 'activity_plasma_scientific_prepare' then activity_plasma_scientific_prepare__count end),0) as activity_plasma_scientific_prepare__count,
ifnull(sum(case when event_name = 'questionnaire' then questionnaire__count end),0) as questionnaire__count,
ifnull(sum(case when event_name = 'zombie_boss' then zombie_boss__count end),0) as zombie_boss__count,
ifnull(sum(case when event_name = 'remote_config' then remote_config__count end),0) as remote_config__count,
ifnull(sum(case when event_name = 'alliance_shop' then alliance_shop__count end),0) as alliance_shop__count,
if(sum(case when event_name = 'Stroy_Collect_Complete' then Stroy_Collect_Complete__flag end)>0,1,0) as Stroy_Collect_Complete__flag,
ifnull(sum(case when event_name = 'today_first_login' then today_first_login__count end),0) as today_first_login__count,
ifnull(sum(case when event_name = 'activity_wd_seek' then activity_wd_seek__count end),0) as activity_wd_seek__count,
ifnull(sum(case when event_name = 'honor_pass_2' then honor_pass_2__count end),0) as honor_pass_2__count,
ifnull(sum(case when event_name = 'train_troop_finish' then train_troop_finish__count end),0) as train_troop_finish__count,
ifnull(sum(case when event_name = 'live_streaming' then live_streaming__count end),0) as live_streaming__count,
ifnull(sum(case when event_name = 'timer_chest_gain' then timer_chest_gain__count end),0) as timer_chest_gain__count,
ifnull(sum(case when event_name = 'gold_event_season' then gold_event_season__count end),0) as gold_event_season__count,
ifnull(sum(case when event_name = 'building_upgrade_finish' then building_upgrade_finish__count end),0) as building_upgrade_finish__count,
ifnull(sum(case when event_name = 'quest_complete' then quest_complete__count end),0) as quest_complete__count,
ifnull(sum(case when event_name = 'chapter_quest_complete' then chapter_quest_complete__count end),0) as chapter_quest_complete__count,
ifnull(sum(case when event_name = 'upgrade_clue' then upgrade_clue__count end),0) as upgrade_clue__count,
ifnull(sum(case when event_name = 'dialog' then dialog__count end),0) as dialog__count,
ifnull(sum(case when event_name = 'leave_alliance' then leave_alliance__count end),0) as leave_alliance__count,
ifnull(sum(case when event_name = 'survivor_support' then survivor_support__count end),0) as survivor_support__count,
ifnull(sum(case when event_name = 'lord_level_up' then lord_level_up__count end),0) as lord_level_up__count,
ifnull(sum(case when event_name = 'localization_signin' then localization_signin__count end),0) as localization_signin__count,
ifnull(sum(case when event_name = 'analysis_center_war' then analysis_center_war__count end),0) as analysis_center_war__count,
ifnull(sum(case when event_name = 'go_back_claim_login_reward' then go_back_claim_login_reward__count end),0) as go_back_claim_login_reward__count,
ifnull(sum(case when event_name = 'go_back_claim_free_iap' then go_back_claim_free_iap__count end),0) as go_back_claim_free_iap__count,
ifnull(sum(case when event_name = 'halloween_event' then halloween_event__count end),0) as halloween_event__count,
ifnull(sum(case when event_name = 'battle' then battle__count end),0) as battle__count,
ifnull(sum(case when event_name = 'disband_alliance' then disband_alliance__count end),0) as disband_alliance__count,
ifnull(sum(case when event_name = 'gain_reward' then gain_reward__count end),0) as gain_reward__count,
ifnull(sum(case when event_name = 'combat' then combat__count end),0) as combat__count,
ifnull(sum(case when event_name = 'alliance_help' then alliance_help__count end),0) as alliance_help__count,
ifnull(sum(case when event_name = 'vip' then vip__count end),0) as vip__count,
ifnull(sum(case when event_name = 'research_finish' then research_finish__count end),0) as research_finish__count,
ifnull(sum(case when event_name = 'login_lord_equipment' then login_lord_equipment__count end),0) as login_lord_equipment__count,
ifnull(sum(case when event_name = 'alliance_iap_gift' then alliance_iap_gift__count end),0) as alliance_iap_gift__count,
ifnull(sum(case when event_name = 'buff_change' then buff_change__count end),0) as buff_change__count,
ifnull(sum(case when event_name = 'research_quest_complete' then research_quest_complete__count end),0) as research_quest_complete__count,
ifnull(sum(case when event_name = 'battle_gather' then battle_gather__count end),0) as battle_gather__count,
ifnull(sum(case when event_name = 'talent_skill' then talent_skill__count end),0) as talent_skill__count,
ifnull(sum(case when event_name = 'chapter_group_start' then chapter_group_start__count end),0) as chapter_group_start__count,
ifnull(sum(case when event_name = 'hidden_exploration' then hidden_exploration__count end),0) as hidden_exploration__count,
ifnull(sum(case when event_name = 'battle_monster' then battle_monster__count end),0) as battle_monster__count,
ifnull(sum(case when event_name = 'join_alliance' then join_alliance__count end),0) as join_alliance__count,
ifnull(sum(case when event_name = 'world_line' then world_line__count end),0) as world_line__count,
ifnull(sum(case when event_name = 'localization_exchange_event' then localization_exchange_event__count end),0) as localization_exchange_event__count,
ifnull(sum(case when event_name = 'prosperity' then prosperity__count end),0) as prosperity__count,
ifnull(sum(case when event_name = 'festival_region_pass' then festival_region_pass__count end),0) as festival_region_pass__count,
ifnull(sum(case when event_name = 'alliance_tech' then alliance_tech__count end),0) as alliance_tech__count,
ifnull(sum(case when event_name = 'chapter_group_complete' then chapter_group_complete__count end),0) as chapter_group_complete__count,
ifnull(sum(case when event_name = 'go_back_sprint_quest_complete' then go_back_sprint_quest_complete__count end),0) as go_back_sprint_quest_complete__count,
ifnull(sum(case when event_name = 'activity_advance_research_five_days' then activity_advance_research_five_days__count end),0) as activity_advance_research_five_days__count,
ifnull(sum(case when event_name = 'alliance_request' then alliance_request__count end),0) as alliance_request__count,
ifnull(sum(case when event_name = 'alliance_mark' then alliance_mark__count end),0) as alliance_mark__count,
ifnull(sum(case when event_name = 'explore_loading' then explore_loading__count end),0) as explore_loading__count,
ifnull(sum(case when event_name = 'dress_up' then dress_up__count end),0) as dress_up__count,
ifnull(sum(case when event_name = 'exchange_code' then exchange_code__count end),0) as exchange_code__count,
ifnull(sum(case when event_name = 'dismiss_troop' then dismiss_troop__count end),0) as dismiss_troop__count,
ifnull(sum(case when event_name = 'go_back' then go_back__count end),0) as go_back__count,
ifnull(sum(case when event_name = 'fresher_pease_shield' then fresher_pease_shield__count end),0) as fresher_pease_shield__count,
ifnull(sum(case when event_name = 'user_agreement' then user_agreement__count end),0) as user_agreement__count,
ifnull(sum(case when event_name = 'world_event_season_sign' then world_event_season_sign__count end),0) as world_event_season_sign__count,
ifnull(sum(case when event_name = 'week_card' then week_card__count end),0) as week_card__count,
ifnull(sum(case when event_name = 'activity_survivor_seven_days' then activity_survivor_seven_days__count end),0) as activity_survivor_seven_days__count,
ifnull(sum(case when event_name = 'supplememt_tropps_base' then supplememt_tropps_base__count end),0) as supplememt_tropps_base__count,
ifnull(sum(case when event_name = 'activity_red_packet' then activity_red_packet__count end),0) as activity_red_packet__count,
ifnull(sum(case when event_name = 'battle_power_change' then battle_power_change__change_power end),0) as battle_power_change__change_power,
ifnull(sum(case when event_name = 'wd_daryl_get_reward' then wd_daryl_get_reward__count end),0) as wd_daryl_get_reward__count,
ifnull(sum(case when event_name = 'avaleague_quest' then avaleague_quest__count end),0) as avaleague_quest__count,
ifnull(sum(case when event_name = 'city_buff' then city_buff__count end),0) as city_buff__count,
ifnull(sum(case when event_name = 'big_timer_chest' then big_timer_chest__count end),0) as big_timer_chest__count,
ifnull(sum(case when event_name = 'survivor_unlock' then survivor_unlock__count end),0) as survivor_unlock__count,
ifnull(sum(case when event_name = 'custom_iap_2' then custom_iap_2__count end),0) as custom_iap_2__count,
ifnull(sum(case when event_name = 'hero_drop' then hero_drop__count end),0) as hero_drop__count,
ifnull(sum(case when event_name = 'tutorial_ex' then tutorial_ex__count end),0) as tutorial_ex__count,
ifnull(sum(case when event_name = 'unlock_city_block_v3' then unlock_city_block_v3__count end),0) as unlock_city_block_v3__count,
ifnull(sum(case when event_name = 'exchange_survivor_chip' then exchange_survivor_chip__count end),0) as exchange_survivor_chip__count,
ifnull(sum(case when event_name = 'kingdom_war' then kingdom_war__count end),0) as kingdom_war__count,
ifnull(sum(case when event_name = 'plasma_building_prepare' then plasma_building_prepare__count end),0) as plasma_building_prepare__count,
ifnull(sum(case when event_name = 'gameStoreScore' then gameStoreScore__count end),0) as gameStoreScore__count,
ifnull(sum(case when event_name = 'growth_fund' then growth_fund__count end),0) as growth_fund__count,
ifnull(sum(case when event_name = 'kvk' then kvk__count end),0) as kvk__count,
ifnull(sum(case when event_name = 'wd_user_draw_real_reward' then wd_user_draw_real_reward__count end),0) as wd_user_draw_real_reward__count,
ifnull(sum(case when event_name = 'kvk_recuperate' then kvk_recuperate__count end),0) as kvk_recuperate__count,
if(sum(case when event_name = 'heal_troop' then heal_troop__flag end)>0,1,0) as heal_troop__flag,
ifnull(sum(case when event_name = 'donate' then donate__tot_times end),0) as donate__tot_times,
ifnull(sum(case when event_name = 'ask_alliance_help' then ask_alliance_help__count end),0) as ask_alliance_help__count,
ifnull(sum(case when event_name = 'view_other_city' then view_other_city__count end),0) as view_other_city__count,
ifnull(sum(case when event_name = 'alliance_boss' then alliance_boss__count end),0) as alliance_boss__count,
ifnull(sum(case when event_name = 'survivor_search' then survivor_search__count end),0) as survivor_search__count,
ifnull(sum(case when event_name = 'reward_center' then reward_center__count end),0) as reward_center__count,
ifnull(sum(case when event_name = 'alliance_donate_rank' then alliance_donate_rank__count end),0) as alliance_donate_rank__count,
ifnull(sum(case when event_name = 'survivor' then survivor__count end),0) as survivor__count,
ifnull(sum(case when event_name = 'user_vault' then user_vault__count end),0) as user_vault__count,
ifnull(sum(case when event_name = 'poison_land' then poison_land__count end),0) as poison_land__count,
ifnull(sum(case when event_name = 'battle_pvp_detail' then battle_pvp_detail__count end),0) as battle_pvp_detail__count,
ifnull(sum(case when event_name = 'seven_day' then seven_day__count end),0) as seven_day__count,
ifnull(sum(case when event_name = 'chapter_quest_gain_quest_reward' then chapter_quest_gain_quest_reward__count end),0) as chapter_quest_gain_quest_reward__count,
ifnull(sum(case when event_name = 'zombie_invasion' then zombie_invasion__count end),0) as zombie_invasion__count,
ifnull(sum(case when event_name = 'exploration' then exploration__count end),0) as exploration__count,
ifnull(sum(case when event_name = 'lord_equipment_gem_power' then lord_equipment_gem_power__change_power end),0) as lord_equipment_gem_power__change_power,
ifnull(sum(case when event_name = 'IapPaymentSuccess' then IapPaymentSuccess__count end),0) as IapPaymentSuccess__count,
ifnull(sum(case when event_name = 'survivor_camp' then survivor_camp__count end),0) as survivor_camp__count,
ifnull(sum(case when event_name = 'hide_troop' then hide_troop__hided_troops_power end),0) as hide_troop__hided_troops_power,
ifnull(sum(case when event_name = 'europe_policy' then europe_policy__count end),0) as europe_policy__count,
ifnull(sum(case when event_name = 'micro_com' then micro_com__count end),0) as micro_com__count,
ifnull(sum(case when event_name = 'activity_daily_iap_accumulative_reward' then activity_daily_iap_accumulative_reward__count end),0) as activity_daily_iap_accumulative_reward__count,
ifnull(sum(case when event_name = 'powerup' then powerup__count end),0) as powerup__count,
ifnull(sum(case when event_name = 'roguelike' then roguelike__count end),0) as roguelike__count,
ifnull(sum(case when event_name = 'claim_sprint_box_reward' then claim_sprint_box_reward__count end),0) as claim_sprint_box_reward__count,
ifnull(sum(case when event_name = 'go_back_new_world' then go_back_new_world__count end),0) as go_back_new_world__count,
ifnull(sum(case when event_name = 'unlock_city_block' then unlock_city_block__count end),0) as unlock_city_block__count,
ifnull(sum(case when event_name = 'supplememt_tropps' then supplememt_tropps__count end),0) as supplememt_tropps__count,
ifnull(sum(case when event_name = 'loading' then loading__count end),0) as loading__count,
ifnull(sum(case when event_name = 'city_decoration' then city_decoration__count end),0) as city_decoration__count,
ifnull(sum(case when event_name = 'stamina' then stamina__count end),0) as stamina__count,
ifnull(sum(case when event_name = 'big_turntable' then big_turntable__count end),0) as big_turntable__count,
ifnull(sum(case when event_name = 'wd_daryl_new_clue_gained' then wd_daryl_new_clue_gained__count end),0) as wd_daryl_new_clue_gained__count,
ifnull(sum(case when event_name = 'train_troop' then train_troop__count end),0) as train_troop__count,
ifnull(sum(case when event_name = 'story' then story__count end),0) as story__count,
if(sum(case when event_name = 'research_upgrade' then research_upgrade__flag end)>0,1,0) as research_upgrade__flag,
ifnull(sum(case when event_name = 'alliance_speedup' then alliance_speedup__count end),0) as alliance_speedup__count,
ifnull(sum(case when event_name = 'custom_iap_3' then custom_iap_3__count end),0) as custom_iap_3__count,
ifnull(sum(case when event_name = 'shop' then shop__count end),0) as shop__count,
ifnull(sum(case when event_name = 'login' then login__count end),0) as login__count,
if(sum(case when event_name = 'cheat_user' then cheat_user__flag end)>0,1,0) as cheat_user__flag,
ifnull(sum(case when event_name = 'kingdom_event' then kingdom_event__count end),0) as kingdom_event__count,
ifnull(sum(case when event_name = 'world_event' then world_event__count end),0) as world_event__count,
ifnull(sum(case when event_name = 'quest_gain_reward' then quest_gain_reward__count end),0) as quest_gain_reward__count,
ifnull(sum(case when event_name = 'payment_submit_order' then payment_submit_order__count end),0) as payment_submit_order__count,
ifnull(sum(case when event_name = 'chapter_quest_gain_group_reward' then chapter_quest_gain_group_reward__count end),0) as chapter_quest_gain_group_reward__count,
ifnull(sum(case when event_name = 'survivor_will' then survivor_will__count end),0) as survivor_will__count,
ifnull(sum(case when event_name = 'forge_equipment' then forge_equipment__count end),0) as forge_equipment__count,
ifnull(sum(case when event_name = 'alliance_zone' then alliance_zone__count end),0) as alliance_zone__count,
ifnull(sum(case when event_name = 'survivor_summon' then survivor_summon__count end),0) as survivor_summon__count,
if(sum(case when event_name = 'city_fire' then city_fire__flag end)>0,1,0) as city_fire__flag,
ifnull(sum(case when event_name = 'buy_month_card' then buy_month_card__count end),0) as buy_month_card__count,
ifnull(sum(case when event_name = 'survivor_link' then survivor_link__count end),0) as survivor_link__count,
ifnull(sum(case when event_name = 'create_alliance' then create_alliance__count end),0) as create_alliance__count,
ifnull(sum(case when event_name = 'iap_exchange' then iap_exchange__count end),0) as iap_exchange__count,
ifnull(sum(case when event_name = 'super_exchange' then super_exchange__count end),0) as super_exchange__count,
ifnull(sum(case when event_name = 'charge_first_pass' then charge_first_pass__count end),0) as charge_first_pass__count,
ifnull(sum(case when event_name = 'switch_kingdom' then switch_kingdom__count end),0) as switch_kingdom__count,
ifnull(sum(case when event_name = 'activity_gift' then activity_gift__count end),0) as activity_gift__count,
ifnull(sum(case when event_name = 'tutorial' then tutorial__count end),0) as tutorial__count,
ifnull(sum(case when event_name = 'survivor_equipment' then survivor_equipment__count end),0) as survivor_equipment__count,
ifnull(sum(case when event_name = 'npc_store' then npc_store__count end),0) as npc_store__count,
ifnull(sum(case when event_name = 'wd_user_answer_question' then wd_user_answer_question__count end),0) as wd_user_answer_question__count,
ifnull(sum(case when event_name = 'alliance_mobilization' then alliance_mobilization__count end),0) as alliance_mobilization__count,
ifnull(sum(case when event_name = 'intelligence_stamina' then intelligence_stamina__change end),0) as intelligence_stamina__change,
ifnull(sum(case when event_name = 'dynamic_recommend_iap' then dynamic_recommend_iap__count end),0) as dynamic_recommend_iap__count,
ifnull(sum(case when event_name = 'upgrade_troop' then upgrade_troop__count end),0) as upgrade_troop__count,
ifnull(sum(case when event_name = 'MarchLine_Click' then MarchLine_Click__count end),0) as MarchLine_Click__count,
if(sum(case when event_name = 'login_survivor_equipment' then login_survivor_equipment__flag end)>0,1,0) as login_survivor_equipment__flag,
ifnull(sum(case when event_name = 'c' then c__count end),0) as c__count,
ifnull(sum(case when event_name = 'fallen_knight' then fallen_knight__count end),0) as fallen_knight__count,
ifnull(sum(case when event_name = 'fallen_knight_defend_success' then fallen_knight_defend_success__count end),0) as fallen_knight_defend_success__count,
ifnull(sum(case when event_name = 'battle_gve' then battle_gve__count end),0) as battle_gve__count,
ifnull(sum(case when event_name = 'user_gem' then user_gem__count end),0) as user_gem__count,
ifnull(sum(case when event_name = 'puzzle_pve' then puzzle_pve__count end),0) as puzzle_pve__count,
ifnull(sum(case when event_name = 'lord_equipment_power' then lord_equipment_power__count end),0) as lord_equipment_power__count,
ifnull(sum(case when event_name = 'hunter_house' then hunter_house__count end),0) as hunter_house__count,
ifnull(sum(case when event_name = 'cultivate' then cultivate__count end),0) as cultivate__count,
ifnull(sum(case when event_name = 'plasma_cannon' then plasma_cannon__count end),0) as plasma_cannon__count,
ifnull(sum(case when event_name = 'go_back_claim_sprint_quest_reward' then go_back_claim_sprint_quest_reward__count end),0) as go_back_claim_sprint_quest_reward__count,
ifnull(sum(case when event_name = 'storyline' then storyline__count end),0) as storyline__count,
ifnull(sum(case when event_name = 'iap_trigger' then iap_trigger__count end),0) as iap_trigger__count,
ifnull(sum(case when event_name = 'wounded_reward' then wounded_reward__lost_power end),0) as wounded_reward__lost_power,
ifnull(sum(case when event_name = 'advance_research_finish' then advance_research_finish__count end),0) as advance_research_finish__count,
ifnull(sum(case when event_name = 'go_back_user_info' then go_back_user_info__count end),0) as go_back_user_info__count,
ifnull(sum(case when event_name = 'festival_pass' then festival_pass__count end),0) as festival_pass__count,
ifnull(sum(case when event_name = 'wd_daryl_clue_compose' then wd_daryl_clue_compose__count end),0) as wd_daryl_clue_compose__count,
ifnull(sum(case when event_name = 'payment_pay_type' then payment_pay_type__count end),0) as payment_pay_type__count,
ifnull(sum(case when event_name = 'user_skill' then user_skill__count end),0) as user_skill__count,
ifnull(sum(case when event_name = 'walking_dead_event' then walking_dead_event__count end),0) as walking_dead_event__count,
ifnull(sum(case when event_name = 'mini_wonder_war' then mini_wonder_war__count end),0) as mini_wonder_war__count,
ifnull(sum(case when event_name = 'faq1_0' then faq1_0__count end),0) as faq1_0__count,
ifnull(sum(case when event_name = 'buy_week_card' then buy_week_card__count end),0) as buy_week_card__count,
ifnull(sum(case when event_name = 'stronghold_level_reward' then stronghold_level_reward__count end),0) as stronghold_level_reward__count,
ifnull(sum(case when event_name = 'world_event_memorial_book_abyss' then world_event_memorial_book_abyss__count end),0) as world_event_memorial_book_abyss__count,
ifnull(sum(case when event_name = 'festival_wish' then festival_wish__count end),0) as festival_wish__count,
ifnull(sum(case when event_name = 'festival_collection' then festival_collection__count end),0) as festival_collection__count,
if(sum(case when event_name = 'focus_out' then focus_out__flag end)>0,1,0) as focus_out__flag,
ifnull(sum(case when event_name = 'MonthCard' then MonthCard__count end),0) as MonthCard__count,
if(sum(case when event_name = 'focus_in' then focus_in__flag end)>0,1,0) as focus_in__flag,
ifnull(sum(case when event_name = 'activity_limit_time_discount_shop' then activity_limit_time_discount_shop__count end),0) as activity_limit_time_discount_shop__count,
ifnull(sum(case when event_name = 'micro_com1_1' then micro_com1_1__count end),0) as micro_com1_1__count,
ifnull(sum(case when event_name = 'go_back_claim_sprint_task_reward' then go_back_claim_sprint_task_reward__count end),0) as go_back_claim_sprint_task_reward__count,
ifnull(sum(case when event_name = 'march' then march__count end),0) as march__count,
ifnull(sum(case when event_name = 'transaction' then transaction__count end),0) as transaction__count,
ifnull(sum(case when event_name = 'festival_boss' then festival_boss__count end),0) as festival_boss__count,
ifnull(sum(case when event_name = 'wd_collection' then wd_collection__count end),0) as wd_collection__count,
ifnull(sum(case when event_name = 'avaleague' then avaleague__count end),0) as avaleague__count,
ifnull(sum(case when event_name = 'avaleague_guess' then avaleague_guess__count end),0) as avaleague_guess__count,
ifnull(sum(case when event_name = 'exchange_gifts' then exchange_gifts__count end),0) as exchange_gifts__count,
if(sum(case when event_name = 'auto_fix_date' then auto_fix_date__flag end)>0,1,0) as auto_fix_date__flag,
ifnull(sum(case when event_name = 'festival_navigation' then festival_navigation__count end),0) as festival_navigation__count,
ifnull(sum(case when event_name = 'lord_gem_verification_attack_boss_finish' then lord_gem_verification_attack_boss_finish__count end),0) as lord_gem_verification_attack_boss_finish__count,
ifnull(sum(case when event_name = 'open_fallen_knight' then open_fallen_knight__count end),0) as open_fallen_knight__count,
ifnull(sum(case when event_name = 'lord_gem_verification_quest_complete' then lord_gem_verification_quest_complete__count end),0) as lord_gem_verification_quest_complete__count,
ifnull(sum(case when event_name = 'action' then action__count end),0) as action__count,
ifnull(sum(case when event_name = 'anti_addiction' then anti_addiction__count end),0) as anti_addiction__count,
ifnull(sum(case when event_name = 'climbing_tower' then climbing_tower__count end),0) as climbing_tower__count,
ifnull(sum(case when event_name = 'festival_story' then festival_story__count end),0) as festival_story__count,
ifnull(sum(case when event_name = 'new_big_turntable' then new_big_turntable__count end),0) as new_big_turntable__count,
ifnull(sum(case when event_name = 'festival_zodiac_collect' then festival_zodiac_collect__count end),0) as festival_zodiac_collect__count,
ifnull(sum(case when event_name = 'startDailyQuestBI' then startDailyQuestBI__count end),0) as startDailyQuestBI__count,
ifnull(sum(case when event_name = 'lord_gem_verification_attack_boss_start' then lord_gem_verification_attack_boss_start__count end),0) as lord_gem_verification_attack_boss_start__count,
ifnull(sum(case when event_name = 'lord_gem_verification_combat_ready_receive' then lord_gem_verification_combat_ready_receive__count end),0) as lord_gem_verification_combat_ready_receive__count,
ifnull(sum(case when event_name = 'abyss' then abyss__count end),0) as abyss__count,
ifnull(sum(case when event_name = 'honor_pass' then honor_pass__count end),0) as honor_pass__count,
ifnull(sum(case when event_name = 'hero_flip_card_over' then hero_flip_card_over__count end),0) as hero_flip_card_over__count,
if(sum(case when event_name = 'launch_start' then launch_start__flag end)>0,1,0) as launch_start__flag,
ifnull(sum(case when event_name = 'lord_gem_verification_quest_receive' then lord_gem_verification_quest_receive__count end),0) as lord_gem_verification_quest_receive__count,
ifnull(sum(case when event_name = 'activity_festival_equip_seven_days' then activity_festival_equip_seven_days__count end),0) as activity_festival_equip_seven_days__count,
ifnull(sum(case when event_name = 'lord_gem_verification_rank' then lord_gem_verification_rank__count end),0) as lord_gem_verification_rank__count,
ifnull(sum(case when event_name = 'world_open' then world_open__count end),0) as world_open__count,
ifnull(sum(case when event_name = 'season_climb_tower' then season_climb_tower__count end),0) as season_climb_tower__count,
ifnull(sum(case when event_name = 'treasure_discover' then treasure_discover__count end),0) as treasure_discover__count,
ifnull(sum(case when event_name = 'noteBookWithoutAlliance' then noteBookWithoutAlliance__count end),0) as noteBookWithoutAlliance__count,
ifnull(sum(case when event_name = 'throne_shock_relocation' then throne_shock_relocation__count end),0) as throne_shock_relocation__count,
ifnull(sum(case when event_name = 'lord_gem_verification_buff_change' then lord_gem_verification_buff_change__count end),0) as lord_gem_verification_buff_change__count,
ifnull(sum(case when event_name = 'friend_list_option' then friend_list_option__count end),0) as friend_list_option__count,
ifnull(sum(case when event_name = 'festival_pass_2' then festival_pass_2__count end),0) as festival_pass_2__count,
ifnull(sum(case when event_name = 'submitDailyQuestBI' then submitDailyQuestBI__count end),0) as submitDailyQuestBI__count,
ifnull(sum(case when event_name = 'exchange_event' then exchange_event__count end),0) as exchange_event__count,
ifnull(sum(case when event_name = 'invite_new_user' then invite_new_user__count end),0) as invite_new_user__count,
ifnull(sum(case when event_name = 'start_gather_march' then start_gather_march__count end),0) as start_gather_march__count,
ifnull(sum(case when event_name = 'activity_recycle' then activity_recycle__count end),0) as activity_recycle__count,
ifnull(sum(case when event_name = 'achievement' then achievement__count end),0) as achievement__count,
ifnull(sum(case when event_name = 'session_start' then session_start__count end),0) as session_start__count,
ifnull(sum(case when event_name = 'dialog_skip' then dialog_skip__count end),0) as dialog_skip__count,
ifnull(sum(case when event_name = 'lord_gem_verification_ready_open' then lord_gem_verification_ready_open__count end),0) as lord_gem_verification_ready_open__count,
ifnull(sum(case when event_name = 'lord_gem_verification_score_quest_complete' then lord_gem_verification_score_quest_complete__count end),0) as lord_gem_verification_score_quest_complete__count,
ifnull(sum(case when event_name = 'world_event_memorial_book_kvk' then world_event_memorial_book_kvk__count end),0) as world_event_memorial_book_kvk__count,
ifnull(sum(case when event_name = 'equipment_signin' then equipment_signin__count end),0) as equipment_signin__count,
ifnull(sum(case when event_name = 'daily_sign_in' then daily_sign_in__count end),0) as daily_sign_in__count,
ifnull(sum(case when event_name = 'ava' then ava__count end),0) as ava__count,
ifnull(sum(case when event_name = 'session_en' then session_en__count end),0) as session_en__count,
ifnull(sum(case when event_name = 'super_exchange_2' then super_exchange_2__count end),0) as super_exchange_2__count,
ifnull(sum(case when event_name = 'wd_lottery' then wd_lottery__count end),0) as wd_lottery__count,
ifnull(sum(case when event_name = 'service_monitoring' then service_monitoring__count end),0) as service_monitoring__count,
ifnull(sum(case when event_name = 'alliance_trade' then alliance_trade__count end),0) as alliance_trade__count,
ifnull(sum(case when event_name = 'activity_drop' then activity_drop__count end),0) as activity_drop__count,
ifnull(sum(case when event_name = 'session_end' then session_end__count end),0) as session_end__count,
ifnull(sum(case when event_name = 'lord_gem_verification_ready_score_change' then lord_gem_verification_ready_score_change__count end),0) as lord_gem_verification_ready_score_change__count,
ifnull(sum(case when event_name = 'event_SS_Revenue' then event_SS_Revenue__value_in_usd end),0) as event_SS_Revenue__value_in_usd,
if(sum(case when event_name = 'first_open' then first_open__flag end)>0,1,0) as first_open__flag
from data_flat_1
group by universal_user_id, event_date 
) 
select 
a.*, 
ifnull(b.login_flag,0) as login_flag, 
ifnull(b.pay_flag,0) as pay_flag, 
 ifnull(b.login_music_state__flag,0) as login_music_state__flag,
ifnull(b.track_auth__count,0) as track_auth__count,
ifnull(b.wd_daryl_unlock_new_buildings__count,0) as wd_daryl_unlock_new_buildings__count,
ifnull(b.intel_v2__count,0) as intel_v2__count,
ifnull(b.daily_reward__count,0) as daily_reward__count,
ifnull(b.gold_event__count,0) as gold_event__count,
ifnull(b.se_battle__count,0) as se_battle__count,
ifnull(b.gather__count,0) as gather__count,
ifnull(b.custom_iap__count,0) as custom_iap__count,
ifnull(b.login_lord_gem__count,0) as login_lord_gem__count,
ifnull(b.month_card__count,0) as month_card__count,
ifnull(b.building_upgrade__count,0) as building_upgrade__count,
ifnull(b.CMS__count,0) as CMS__count,
ifnull(b.Halloween_Candy__count,0) as Halloween_Candy__count,
ifnull(b.lord_gem_verification_not_received__count,0) as lord_gem_verification_not_received__count,
ifnull(b.alliance_craft__count,0) as alliance_craft__count,
ifnull(b.score_special__count,0) as score_special__count,
ifnull(b.scout__count,0) as scout__count,
ifnull(b.teleport__count,0) as teleport__count,
ifnull(b.recharge_rebate__count,0) as recharge_rebate__count,
ifnull(b.gameLike__count,0) as gameLike__count,
ifnull(b.advance_research_upgrade__count,0) as advance_research_upgrade__count,
ifnull(b.festival_daily_task__count,0) as festival_daily_task__count,
ifnull(b.change_equipment__count,0) as change_equipment__count,
ifnull(b.ab_test__count,0) as ab_test__count,
ifnull(b.kingdom_war_pve__count,0) as kingdom_war_pve__count,
ifnull(b.wd_user_get_quest_reward__count,0) as wd_user_get_quest_reward__count,
ifnull(b.activity_festival_seven_days__count,0) as activity_festival_seven_days__count,
ifnull(b.iap_charge_continuous__count,0) as iap_charge_continuous__count,
ifnull(b.activity_plasma_scientific_prepare__count,0) as activity_plasma_scientific_prepare__count,
ifnull(b.questionnaire__count,0) as questionnaire__count,
ifnull(b.zombie_boss__count,0) as zombie_boss__count,
ifnull(b.remote_config__count,0) as remote_config__count,
ifnull(b.alliance_shop__count,0) as alliance_shop__count,
ifnull(b.Stroy_Collect_Complete__flag,0) as Stroy_Collect_Complete__flag,
ifnull(b.today_first_login__count,0) as today_first_login__count,
ifnull(b.activity_wd_seek__count,0) as activity_wd_seek__count,
ifnull(b.honor_pass_2__count,0) as honor_pass_2__count,
ifnull(b.train_troop_finish__count,0) as train_troop_finish__count,
ifnull(b.live_streaming__count,0) as live_streaming__count,
ifnull(b.timer_chest_gain__count,0) as timer_chest_gain__count,
ifnull(b.gold_event_season__count,0) as gold_event_season__count,
ifnull(b.building_upgrade_finish__count,0) as building_upgrade_finish__count,
ifnull(b.quest_complete__count,0) as quest_complete__count,
ifnull(b.chapter_quest_complete__count,0) as chapter_quest_complete__count,
ifnull(b.upgrade_clue__count,0) as upgrade_clue__count,
ifnull(b.dialog__count,0) as dialog__count,
ifnull(b.leave_alliance__count,0) as leave_alliance__count,
ifnull(b.survivor_support__count,0) as survivor_support__count,
ifnull(b.lord_level_up__count,0) as lord_level_up__count,
ifnull(b.localization_signin__count,0) as localization_signin__count,
ifnull(b.analysis_center_war__count,0) as analysis_center_war__count,
ifnull(b.go_back_claim_login_reward__count,0) as go_back_claim_login_reward__count,
ifnull(b.go_back_claim_free_iap__count,0) as go_back_claim_free_iap__count,
ifnull(b.halloween_event__count,0) as halloween_event__count,
ifnull(b.battle__count,0) as battle__count,
ifnull(b.disband_alliance__count,0) as disband_alliance__count,
ifnull(b.gain_reward__count,0) as gain_reward__count,
ifnull(b.combat__count,0) as combat__count,
ifnull(b.alliance_help__count,0) as alliance_help__count,
ifnull(b.vip__count,0) as vip__count,
ifnull(b.research_finish__count,0) as research_finish__count,
ifnull(b.login_lord_equipment__count,0) as login_lord_equipment__count,
ifnull(b.alliance_iap_gift__count,0) as alliance_iap_gift__count,
ifnull(b.buff_change__count,0) as buff_change__count,
ifnull(b.research_quest_complete__count,0) as research_quest_complete__count,
ifnull(b.battle_gather__count,0) as battle_gather__count,
ifnull(b.talent_skill__count,0) as talent_skill__count,
ifnull(b.chapter_group_start__count,0) as chapter_group_start__count,
ifnull(b.hidden_exploration__count,0) as hidden_exploration__count,
ifnull(b.battle_monster__count,0) as battle_monster__count,
ifnull(b.join_alliance__count,0) as join_alliance__count,
ifnull(b.world_line__count,0) as world_line__count,
ifnull(b.localization_exchange_event__count,0) as localization_exchange_event__count,
ifnull(b.prosperity__count,0) as prosperity__count,
ifnull(b.festival_region_pass__count,0) as festival_region_pass__count,
ifnull(b.alliance_tech__count,0) as alliance_tech__count,
ifnull(b.chapter_group_complete__count,0) as chapter_group_complete__count,
ifnull(b.go_back_sprint_quest_complete__count,0) as go_back_sprint_quest_complete__count,
ifnull(b.activity_advance_research_five_days__count,0) as activity_advance_research_five_days__count,
ifnull(b.alliance_request__count,0) as alliance_request__count,
ifnull(b.alliance_mark__count,0) as alliance_mark__count,
ifnull(b.explore_loading__count,0) as explore_loading__count,
ifnull(b.dress_up__count,0) as dress_up__count,
ifnull(b.exchange_code__count,0) as exchange_code__count,
ifnull(b.dismiss_troop__count,0) as dismiss_troop__count,
ifnull(b.go_back__count,0) as go_back__count,
ifnull(b.fresher_pease_shield__count,0) as fresher_pease_shield__count,
ifnull(b.user_agreement__count,0) as user_agreement__count,
ifnull(b.world_event_season_sign__count,0) as world_event_season_sign__count,
ifnull(b.week_card__count,0) as week_card__count,
ifnull(b.activity_survivor_seven_days__count,0) as activity_survivor_seven_days__count,
ifnull(b.supplememt_tropps_base__count,0) as supplememt_tropps_base__count,
ifnull(b.activity_red_packet__count,0) as activity_red_packet__count,
ifnull(b.battle_power_change__change_power,0) as battle_power_change__change_power,
ifnull(b.wd_daryl_get_reward__count,0) as wd_daryl_get_reward__count,
ifnull(b.avaleague_quest__count,0) as avaleague_quest__count,
ifnull(b.city_buff__count,0) as city_buff__count,
ifnull(b.big_timer_chest__count,0) as big_timer_chest__count,
ifnull(b.survivor_unlock__count,0) as survivor_unlock__count,
ifnull(b.custom_iap_2__count,0) as custom_iap_2__count,
ifnull(b.hero_drop__count,0) as hero_drop__count,
ifnull(b.tutorial_ex__count,0) as tutorial_ex__count,
ifnull(b.unlock_city_block_v3__count,0) as unlock_city_block_v3__count,
ifnull(b.exchange_survivor_chip__count,0) as exchange_survivor_chip__count,
ifnull(b.kingdom_war__count,0) as kingdom_war__count,
ifnull(b.plasma_building_prepare__count,0) as plasma_building_prepare__count,
ifnull(b.gameStoreScore__count,0) as gameStoreScore__count,
ifnull(b.growth_fund__count,0) as growth_fund__count,
ifnull(b.kvk__count,0) as kvk__count,
ifnull(b.wd_user_draw_real_reward__count,0) as wd_user_draw_real_reward__count,
ifnull(b.kvk_recuperate__count,0) as kvk_recuperate__count,
ifnull(b.heal_troop__flag,0) as heal_troop__flag,
ifnull(b.donate__tot_times,0) as donate__tot_times,
ifnull(b.ask_alliance_help__count,0) as ask_alliance_help__count,
ifnull(b.view_other_city__count,0) as view_other_city__count,
ifnull(b.alliance_boss__count,0) as alliance_boss__count,
ifnull(b.survivor_search__count,0) as survivor_search__count,
ifnull(b.reward_center__count,0) as reward_center__count,
ifnull(b.alliance_donate_rank__count,0) as alliance_donate_rank__count,
ifnull(b.survivor__count,0) as survivor__count,
ifnull(b.user_vault__count,0) as user_vault__count,
ifnull(b.poison_land__count,0) as poison_land__count,
ifnull(b.battle_pvp_detail__count,0) as battle_pvp_detail__count,
ifnull(b.seven_day__count,0) as seven_day__count,
ifnull(b.chapter_quest_gain_quest_reward__count,0) as chapter_quest_gain_quest_reward__count,
ifnull(b.zombie_invasion__count,0) as zombie_invasion__count,
ifnull(b.exploration__count,0) as exploration__count,
ifnull(b.lord_equipment_gem_power__change_power,0) as lord_equipment_gem_power__change_power,
ifnull(b.IapPaymentSuccess__count,0) as IapPaymentSuccess__count,
ifnull(b.survivor_camp__count,0) as survivor_camp__count,
ifnull(b.hide_troop__hided_troops_power,0) as hide_troop__hided_troops_power,
ifnull(b.europe_policy__count,0) as europe_policy__count,
ifnull(b.micro_com__count,0) as micro_com__count,
ifnull(b.activity_daily_iap_accumulative_reward__count,0) as activity_daily_iap_accumulative_reward__count,
ifnull(b.powerup__count,0) as powerup__count,
ifnull(b.roguelike__count,0) as roguelike__count,
ifnull(b.claim_sprint_box_reward__count,0) as claim_sprint_box_reward__count,
ifnull(b.go_back_new_world__count,0) as go_back_new_world__count,
ifnull(b.unlock_city_block__count,0) as unlock_city_block__count,
ifnull(b.supplememt_tropps__count,0) as supplememt_tropps__count,
ifnull(b.loading__count,0) as loading__count,
ifnull(b.city_decoration__count,0) as city_decoration__count,
ifnull(b.stamina__count,0) as stamina__count,
ifnull(b.big_turntable__count,0) as big_turntable__count,
ifnull(b.wd_daryl_new_clue_gained__count,0) as wd_daryl_new_clue_gained__count,
ifnull(b.train_troop__count,0) as train_troop__count,
ifnull(b.story__count,0) as story__count,
ifnull(b.research_upgrade__flag,0) as research_upgrade__flag,
ifnull(b.alliance_speedup__count,0) as alliance_speedup__count,
ifnull(b.custom_iap_3__count,0) as custom_iap_3__count,
ifnull(b.shop__count,0) as shop__count,
ifnull(b.login__count,0) as login__count,
ifnull(b.cheat_user__flag,0) as cheat_user__flag,
ifnull(b.kingdom_event__count,0) as kingdom_event__count,
ifnull(b.world_event__count,0) as world_event__count,
ifnull(b.quest_gain_reward__count,0) as quest_gain_reward__count,
ifnull(b.payment_submit_order__count,0) as payment_submit_order__count,
ifnull(b.chapter_quest_gain_group_reward__count,0) as chapter_quest_gain_group_reward__count,
ifnull(b.survivor_will__count,0) as survivor_will__count,
ifnull(b.forge_equipment__count,0) as forge_equipment__count,
ifnull(b.alliance_zone__count,0) as alliance_zone__count,
ifnull(b.survivor_summon__count,0) as survivor_summon__count,
ifnull(b.city_fire__flag,0) as city_fire__flag,
ifnull(b.buy_month_card__count,0) as buy_month_card__count,
ifnull(b.survivor_link__count,0) as survivor_link__count,
ifnull(b.create_alliance__count,0) as create_alliance__count,
ifnull(b.iap_exchange__count,0) as iap_exchange__count,
ifnull(b.super_exchange__count,0) as super_exchange__count,
ifnull(b.charge_first_pass__count,0) as charge_first_pass__count,
ifnull(b.switch_kingdom__count,0) as switch_kingdom__count,
ifnull(b.activity_gift__count,0) as activity_gift__count,
ifnull(b.tutorial__count,0) as tutorial__count,
ifnull(b.survivor_equipment__count,0) as survivor_equipment__count,
ifnull(b.npc_store__count,0) as npc_store__count,
ifnull(b.wd_user_answer_question__count,0) as wd_user_answer_question__count,
ifnull(b.alliance_mobilization__count,0) as alliance_mobilization__count,
ifnull(b.intelligence_stamina__change,0) as intelligence_stamina__change,
ifnull(b.dynamic_recommend_iap__count,0) as dynamic_recommend_iap__count,
ifnull(b.upgrade_troop__count,0) as upgrade_troop__count,
ifnull(b.MarchLine_Click__count,0) as MarchLine_Click__count,
ifnull(b.login_survivor_equipment__flag,0) as login_survivor_equipment__flag,
ifnull(b.c__count,0) as c__count,
ifnull(b.fallen_knight__count,0) as fallen_knight__count,
ifnull(b.fallen_knight_defend_success__count,0) as fallen_knight_defend_success__count,
ifnull(b.battle_gve__count,0) as battle_gve__count,
ifnull(b.user_gem__count,0) as user_gem__count,
ifnull(b.puzzle_pve__count,0) as puzzle_pve__count,
ifnull(b.lord_equipment_power__count,0) as lord_equipment_power__count,
ifnull(b.hunter_house__count,0) as hunter_house__count,
ifnull(b.cultivate__count,0) as cultivate__count,
ifnull(b.plasma_cannon__count,0) as plasma_cannon__count,
ifnull(b.go_back_claim_sprint_quest_reward__count,0) as go_back_claim_sprint_quest_reward__count,
ifnull(b.storyline__count,0) as storyline__count,
ifnull(b.iap_trigger__count,0) as iap_trigger__count,
ifnull(b.wounded_reward__lost_power,0) as wounded_reward__lost_power,
ifnull(b.advance_research_finish__count,0) as advance_research_finish__count,
ifnull(b.go_back_user_info__count,0) as go_back_user_info__count,
ifnull(b.festival_pass__count,0) as festival_pass__count,
ifnull(b.wd_daryl_clue_compose__count,0) as wd_daryl_clue_compose__count,
ifnull(b.payment_pay_type__count,0) as payment_pay_type__count,
ifnull(b.user_skill__count,0) as user_skill__count,
ifnull(b.walking_dead_event__count,0) as walking_dead_event__count,
ifnull(b.mini_wonder_war__count,0) as mini_wonder_war__count,
ifnull(b.faq1_0__count,0) as faq1_0__count,
ifnull(b.buy_week_card__count,0) as buy_week_card__count,
ifnull(b.stronghold_level_reward__count,0) as stronghold_level_reward__count,
ifnull(b.world_event_memorial_book_abyss__count,0) as world_event_memorial_book_abyss__count,
ifnull(b.festival_wish__count,0) as festival_wish__count,
ifnull(b.festival_collection__count,0) as festival_collection__count,
ifnull(b.focus_out__flag,0) as focus_out__flag,
ifnull(b.MonthCard__count,0) as MonthCard__count,
ifnull(b.focus_in__flag,0) as focus_in__flag,
ifnull(b.activity_limit_time_discount_shop__count,0) as activity_limit_time_discount_shop__count,
ifnull(b.micro_com1_1__count,0) as micro_com1_1__count,
ifnull(b.go_back_claim_sprint_task_reward__count,0) as go_back_claim_sprint_task_reward__count,
ifnull(b.march__count,0) as march__count,
ifnull(b.transaction__count,0) as transaction__count,
ifnull(b.festival_boss__count,0) as festival_boss__count,
ifnull(b.wd_collection__count,0) as wd_collection__count,
ifnull(b.avaleague__count,0) as avaleague__count,
ifnull(b.avaleague_guess__count,0) as avaleague_guess__count,
ifnull(b.exchange_gifts__count,0) as exchange_gifts__count,
ifnull(b.auto_fix_date__flag,0) as auto_fix_date__flag,
ifnull(b.festival_navigation__count,0) as festival_navigation__count,
ifnull(b.lord_gem_verification_attack_boss_finish__count,0) as lord_gem_verification_attack_boss_finish__count,
ifnull(b.open_fallen_knight__count,0) as open_fallen_knight__count,
ifnull(b.lord_gem_verification_quest_complete__count,0) as lord_gem_verification_quest_complete__count,
ifnull(b.action__count,0) as action__count,
ifnull(b.anti_addiction__count,0) as anti_addiction__count,
ifnull(b.climbing_tower__count,0) as climbing_tower__count,
ifnull(b.festival_story__count,0) as festival_story__count,
ifnull(b.new_big_turntable__count,0) as new_big_turntable__count,
ifnull(b.festival_zodiac_collect__count,0) as festival_zodiac_collect__count,
ifnull(b.startDailyQuestBI__count,0) as startDailyQuestBI__count,
ifnull(b.lord_gem_verification_attack_boss_start__count,0) as lord_gem_verification_attack_boss_start__count,
ifnull(b.lord_gem_verification_combat_ready_receive__count,0) as lord_gem_verification_combat_ready_receive__count,
ifnull(b.abyss__count,0) as abyss__count,
ifnull(b.honor_pass__count,0) as honor_pass__count,
ifnull(b.hero_flip_card_over__count,0) as hero_flip_card_over__count,
ifnull(b.launch_start__flag,0) as launch_start__flag,
ifnull(b.lord_gem_verification_quest_receive__count,0) as lord_gem_verification_quest_receive__count,
ifnull(b.activity_festival_equip_seven_days__count,0) as activity_festival_equip_seven_days__count,
ifnull(b.lord_gem_verification_rank__count,0) as lord_gem_verification_rank__count,
ifnull(b.world_open__count,0) as world_open__count,
ifnull(b.season_climb_tower__count,0) as season_climb_tower__count,
ifnull(b.treasure_discover__count,0) as treasure_discover__count,
ifnull(b.noteBookWithoutAlliance__count,0) as noteBookWithoutAlliance__count,
ifnull(b.throne_shock_relocation__count,0) as throne_shock_relocation__count,
ifnull(b.lord_gem_verification_buff_change__count,0) as lord_gem_verification_buff_change__count,
ifnull(b.friend_list_option__count,0) as friend_list_option__count,
ifnull(b.festival_pass_2__count,0) as festival_pass_2__count,
ifnull(b.submitDailyQuestBI__count,0) as submitDailyQuestBI__count,
ifnull(b.exchange_event__count,0) as exchange_event__count,
ifnull(b.invite_new_user__count,0) as invite_new_user__count,
ifnull(b.start_gather_march__count,0) as start_gather_march__count,
ifnull(b.activity_recycle__count,0) as activity_recycle__count,
ifnull(b.achievement__count,0) as achievement__count,
ifnull(b.session_start__count,0) as session_start__count,
ifnull(b.dialog_skip__count,0) as dialog_skip__count,
ifnull(b.lord_gem_verification_ready_open__count,0) as lord_gem_verification_ready_open__count,
ifnull(b.lord_gem_verification_score_quest_complete__count,0) as lord_gem_verification_score_quest_complete__count,
ifnull(b.world_event_memorial_book_kvk__count,0) as world_event_memorial_book_kvk__count,
ifnull(b.equipment_signin__count,0) as equipment_signin__count,
ifnull(b.daily_sign_in__count,0) as daily_sign_in__count,
ifnull(b.ava__count,0) as ava__count,
ifnull(b.session_en__count,0) as session_en__count,
ifnull(b.super_exchange_2__count,0) as super_exchange_2__count,
ifnull(b.wd_lottery__count,0) as wd_lottery__count,
ifnull(b.service_monitoring__count,0) as service_monitoring__count,
ifnull(b.alliance_trade__count,0) as alliance_trade__count,
ifnull(b.activity_drop__count,0) as activity_drop__count,
ifnull(b.session_end__count,0) as session_end__count,
ifnull(b.lord_gem_verification_ready_score_change__count,0) as lord_gem_verification_ready_score_change__count,
ifnull(b.event_SS_Revenue__value_in_usd,0) as event_SS_Revenue__value_in_usd,
ifnull(b.first_open__flag,0) as first_open__flag,
current_timestamp() as collect_time 
from full_user_date a 
left join event_agg_by_day b 
on a.universal_user_id=b.universal_user_id
and a.event_date=b.event_date