--This script aggregate by day the events from users, who installed our apps in last N days.  
--Step 1: Run and validate the query below in bigquery 
--Step 2: Create a daily schedule job(aka: schedule_job_A) to write the query result to table_A which contains results from all execution of the schedule job 
 --so their will be duplicate records in table A, the dedup script is in dedup.sql. Save the name of table_A for usage in dedup.sql 
CREATE TEMP FUNCTION
abstract_params(input_arr any type, key_value string,value_field int64) as ( 
(select
  case
     when value_field=1 then safe_cast(input_arr.value.string_value as float64)
     when value_field=2 then safe_cast(input_arr.value.int_value as float64)
     when value_field=3 then input_arr.value.float_value 
     else safe_cast(input_arr.value.double_value as float64)
  end
from unnest(input_arr) as input_arr
where key=key_value
limit 1)
);
with event_window as ( 
select current_date() as event_date union all 
select date_sub(current_date(), interval 1 day) union all 
select date_sub(current_date(), interval 2 day) union all 
select date_sub(current_date(), interval 3 day) union all 
select date_sub(current_date(), interval 4 day) union all 
select date_sub(current_date(), interval 5 day) union all 
select date_sub(current_date(), interval 6 day) union all 
select date_sub(current_date(), interval 7 day) union all 
select date_sub(current_date(), interval 8 day) union all 
select date_sub(current_date(), interval 9 day) union all 
select date_sub(current_date(), interval 10 day) union all 
select date_sub(current_date(), interval 11 day) union all 
select date_sub(current_date(), interval 12 day) union all 
select date_sub(current_date(), interval 13 day) union all 
select date_sub(current_date(), interval 14 day) union all 
select date_sub(current_date(), interval 15 day) union all 
select date_sub(current_date(), interval 16 day) union all 
select date_sub(current_date(), interval 17 day) union all 
select date_sub(current_date(), interval 18 day) union all 
select date_sub(current_date(), interval 19 day) union all 
select date_sub(current_date(), interval 20 day) union all 
select date_sub(current_date(), interval 21 day) union all 
select date_sub(current_date(), interval 22 day) union all 
select date_sub(current_date(), interval 23 day) union all 
select date_sub(current_date(), interval 24 day) union all 
select date_sub(current_date(), interval 25 day) union all 
select date_sub(current_date(), interval 26 day) union all 
select date_sub(current_date(), interval 27 day) union all 
select date_sub(current_date(), interval 28 day) union all 
select date_sub(current_date(), interval 29 day) union all 
select date_sub(current_date(), interval 30 day) union all 
select date_sub(current_date(), interval 31 day) union all 
select date_sub(current_date(), interval 32 day) union all 
select date_sub(current_date(), interval 33 day) union all 
select date_sub(current_date(), interval 34 day) union all 
select date_sub(current_date(), interval 35 day) union all 
select date_sub(current_date(), interval 36 day) union all 
select date_sub(current_date(), interval 37 day) union all 
select date_sub(current_date(), interval 38 day) union all 
select date_sub(current_date(), interval 39 day) union all 
select date_sub(current_date(), interval 40 day) union all 
select date_sub(current_date(), interval 41 day) union all 
select date_sub(current_date(), interval 42 day) union all 
select date_sub(current_date(), interval 43 day) union all 
select date_sub(current_date(), interval 44 day) union all 
select date_sub(current_date(), interval 45 day) union all 
select date_sub(current_date(), interval 46 day) union all 
select date_sub(current_date(), interval 47 day) union all 
select date_sub(current_date(), interval 48 day) union all 
select date_sub(current_date(), interval 49 day) union all 
select date_sub(current_date(), interval 50 day) union all 
select date_sub(current_date(), interval 51 day) union all 
select date_sub(current_date(), interval 52 day) union all 
select date_sub(current_date(), interval 53 day) union all 
select date_sub(current_date(), interval 54 day) union all 
select date_sub(current_date(), interval 55 day) union all 
select date_sub(current_date(), interval 56 day) union all 
select date_sub(current_date(), interval 57 day) union all 
select date_sub(current_date(), interval 58 day) union all 
select date_sub(current_date(), interval 59 day) union all 
select date_sub(current_date(), interval 60 day) 
), 
distinct_user_install_event as ( 
select 
firebase_app_instance_id as universal_user_id, 
date(event_date)  as install_date, 
platform, 
geo.country, 
count(0) 
from `im30-data.im30_bi_ml.lf_mocha` 
where date(event_date)  >= date_sub(current_date(), interval 60 day) 
and event_name= 'completedRegistration' 
group by 1,2,3,4), 
distinct_user_install_event_with_next as ( 
select 
universal_user_id,install_date, platform, country,
ifnull(lag(install_date) over (partition by universal_user_id,platform order by install_date desc),date('9999-12-31')) as next_install_date, 
from distinct_user_install_event
), 
full_user_date as ( 
select 
a.universal_user_id, 
a.install_date, 
a.platform, 
a.country, 
b.event_date 
from distinct_user_install_event_with_next a 
cross join event_window b 
where b.event_date >= a.install_date 
and b.event_date < a.next_install_date 
order by universal_user_id, event_date 
), 
data_flat_1 as ( 
select 
firebase_app_instance_id as universal_user_id, 
event_name, 
date(event_date)  as event_date, 
platform, 
if (event_name in ('appLaunches','completedRegistration'), 1 , 0) as login_flag, 
 if (event_name in ('Pay') , 1 , 0) as pay_flag, 
if (event_name='ArmyMessageHanlder',1,0) as ArmyMessageHanlder__count,
if (event_name='DigGroundClickTipsAfterUpgrade',1,0) as DigGroundClickTipsAfterUpgrade__count,
if (event_name='ArenaLastRecord',1,0) as ArenaLastRecord__count,
if (event_name='PVECheckpointBattleStart',1,0) as PVECheckpointBattleStart__count,
if (event_name='completedRegistration',1,0) as completedRegistration__count,
if (event_name='AllianceApplyList',1,0) as AllianceApplyList__count,
if (event_name='GarageFormationRepairInfo',1,0) as GarageFormationRepairInfo__count,
if (event_name='AddComplete',1,0) as AddComplete__count,
if (event_name='DigGroundStationed',1,0) as DigGroundStationed__count,
if (event_name='AlSiegeWaveRecord',1,0) as AlSiegeWaveRecord__count,
if (event_name='AllianceApplyMsg',1,0) as AllianceApplyMsg__count,
if (event_name='MarkMailStatus',1,0) as MarkMailStatus__count,
if (event_name='ScienceResearch',1,0) as ScienceResearch__count,
if (event_name='PlayerFormationExtensionSave',1,0) as PlayerFormationExtensionSave__count,
if (event_name='ZoneShopRefresh',1,0) as ZoneShopRefresh__count,
if (event_name='AllianceLogBattleView',1,0) as AllianceLogBattleView__count,
if (event_name='ShowStatusItem',1,0) as ShowStatusItem__count,
if (event_name='PlayerFormationClientInfo',1,0) as PlayerFormationClientInfo__count,
if (event_name='DigTradeGetUserProperties',1,0) as DigTradeGetUserProperties__count,
if (event_name='appLaunches',1,0) as appLaunches__count,
if (event_name='PowerRankingHandler',1,0) as PowerRankingHandler__count,
if (event_name='RegionForceRankingHandler',1,0) as RegionForceRankingHandler__count,
if (event_name='BattlePassGetUserBuyAdvanceExp',1,0) as BattlePassGetUserBuyAdvanceExp__count,
if (event_name='LocalPersonalRankInfo',1,0) as LocalPersonalRankInfo__count,
if (event_name='DigUserRecyclingResource',1,0) as DigUserRecyclingResource__count,
if (event_name='GetNewPlayerInfo',1,0) as GetNewPlayerInfo__count,
if (event_name='GetWorldCityInfo',1,0) as GetWorldCityInfo__count,
if (event_name='UserAllianceLevelEffectView',1,0) as UserAllianceLevelEffectView__count,
if (event_name='DigFoodCookCancelAndCook',1,0) as DigFoodCookCancelAndCook__count,
if (event_name='BattleEntrance',1,0) as BattleEntrance__count,
if (event_name='PersonalGiftClicked',1,0) as PersonalGiftClicked__count,
if (event_name='EquipLockHandler',1,0) as EquipLockHandler__count,
if (event_name='AcceptPersonalActivityReward',1,0) as AcceptPersonalActivityReward__count,
if (event_name='AllianceDailyTaskView',1,0) as AllianceDailyTaskView__count,
if (event_name='UseItem', abstract_params(event_params,'num',1) ,null) as UseItem__num,
if (event_name='DigGroundBuildUplevelGold',1,0) as DigGroundBuildUplevelGold__count,
if (event_name='PlayerFormationSave',1,0) as PlayerFormationSave__count,
if (event_name='AllianceMilitaryMeritExchangeItems',1,0) as AllianceMilitaryMeritExchangeItems__count,
if (event_name='DigGroundStationedExp',1,0) as DigGroundStationedExp__count,
if (event_name='UserArmsEffectInfo',1,0) as UserArmsEffectInfo__count,
if (event_name='PowerAllianceRankingHandler',1,0) as PowerAllianceRankingHandler__count,
if (event_name='ArenaReportDetailInfo',1,0) as ArenaReportDetailInfo__count,
if (event_name='HonorEditCmd',1,0) as HonorEditCmd__count,
if (event_name='AllianceTransferServerList',1,0) as AllianceTransferServerList__count,
if (event_name='MailRewardBatch',1,0) as MailRewardBatch__count,
if (event_name='SerialKillingClaimReward',1,0) as SerialKillingClaimReward__count,
if (event_name='ZoneHonorReward',1,0) as ZoneHonorReward__count,
if (event_name='AllianceCrossApplyPreview',1,0) as AllianceCrossApplyPreview__count,
if (event_name='SetShowQuality',1,0) as SetShowQuality__count,
if (event_name='ServerTrendsReward',1,0) as ServerTrendsReward__count,
if (event_name='AllianceRewardAllRemove',1,0) as AllianceRewardAllRemove__count,
if (event_name='CureFinish',1,0) as CureFinish__count,
if (event_name='HonorGetInfoCmd',1,0) as HonorGetInfoCmd__count,
if (event_name='AlSiegePanelReward',1,0) as AlSiegePanelReward__count,
if (event_name='BoxGiftReward',1,0) as BoxGiftReward__count,
if (event_name='PVEGetInfo',1,0) as PVEGetInfo__count,
if (event_name='UserExpeditionLook',1,0) as UserExpeditionLook__count,
if (event_name='LotteryHeroCard',1,0) as LotteryHeroCard__count,
if (event_name='UserExpeditionEffectInfo',1,0) as UserExpeditionEffectInfo__count,
if (event_name='EliteNewRefreshData',1,0) as EliteNewRefreshData__count,
if (event_name='DigGroundBuildUplevel',1,0) as DigGroundBuildUplevel__count,
if (event_name='GetRankingBasePanelInfo',1,0) as GetRankingBasePanelInfo__count,
if (event_name='UserPayReward',1,0) as UserPayReward__count,
if (event_name='AllianceMilitaryMeritGet',1,0) as AllianceMilitaryMeritGet__count,
if (event_name='UserAllianceDevelopDonateView',1,0) as UserAllianceDevelopDonateView__count,
if (event_name='DigHeroHandler',1,0) as DigHeroHandler__count,
if (event_name='LFFormationMarchTime',1,0) as LFFormationMarchTime__count,
if (event_name='ZoneShopExchange',1,0) as ZoneShopExchange__count,
if (event_name='ZoneHonorChange',1,0) as ZoneHonorChange__count,
if (event_name='ZoneShopView',1,0) as ZoneShopView__count,
if (event_name='AllianceReinforceList',1,0) as AllianceReinforceList__count,
if (event_name='AddSoldier',1,0) as AddSoldier__count,
if (event_name='ArenaRematch',1,0) as ArenaRematch__count,
if (event_name='AllianceShopUsrBuyRecord',1,0) as AllianceShopUsrBuyRecord__count,
if (event_name='SoldierUpgradeComplete',1,0) as SoldierUpgradeComplete__count,
if (event_name='DigFoodCookCancel',1,0) as DigFoodCookCancel__count,
if (event_name='AcceptTaskReward',1,0) as AcceptTaskReward__count,
if (event_name='DigGroundBuildUplevelNoHeroes',1,0) as DigGroundBuildUplevelNoHeroes__count,
if (event_name='AllianceCommentView',1,0) as AllianceCommentView__count,
if (event_name='BuildingRankingHandler',1,0) as BuildingRankingHandler__count,
if (event_name='GetFoodProduce',1,0) as GetFoodProduce__count,
if (event_name='PVEClearanceReplay',1,0) as PVEClearanceReplay__count,
if (event_name='BattlePassGetTaskReward',1,0) as BattlePassGetTaskReward__count,
if (event_name='DeleteBatch',1,0) as DeleteBatch__count,
if (event_name='LotteryHeroCardInfo',1,0) as LotteryHeroCardInfo__count,
if (event_name='TradeStationGetInfo',1,0) as TradeStationGetInfo__count,
if (event_name='UserAllianceLevelGetReward',1,0) as UserAllianceLevelGetReward__count,
if (event_name='EliteNewSelfFightList',1,0) as EliteNewSelfFightList__count,
if (event_name='ArenaUserFightRecordNew',1,0) as ArenaUserFightRecordNew__count,
if (event_name='UserAlliancePointRank',1,0) as UserAlliancePointRank__count,
if (event_name='SerialKillingBuyNum',1,0) as SerialKillingBuyNum__count,
if (event_name='UserExpeditionWard',1,0) as UserExpeditionWard__count,
if (event_name='ExchangeByActivity', abstract_params(event_params,'num',1) ,null) as ExchangeByActivity__num,
if (event_name='BattlePassGetDropExpInfo',1,0) as BattlePassGetDropExpInfo__count,
if (event_name='DigHeroLevelUpPreview',1,0) as DigHeroLevelUpPreview__count,
if (event_name='HeroQualityActGetReward',1,0) as HeroQualityActGetReward__count,
if (event_name='ArenaGetInfo',1,0) as ArenaGetInfo__count,
if (event_name='DigFoodCookCmd', abstract_params(event_params,'number',1) ,null) as DigFoodCookCmd__number,
if (event_name='UserAllianceDevelopView',1,0) as UserAllianceDevelopView__count,
if (event_name='AlSiegeSetAlarm',1,0) as AlSiegeSetAlarm__count,
if (event_name='AddArmyImmediately', abstract_params(event_params,'num',1) ,null) as AddArmyImmediately__num,
if (event_name='EquipUpHandler',1,0) as EquipUpHandler__count,
if (event_name='Pay', abstract_params(event_params,'pay_PriceOfClosingCurrency',1) ,null) as Pay__pay_PriceOfClosingCurrency,
if (event_name='CrossPersonalRankInfo',1,0) as CrossPersonalRankInfo__count,
if (event_name='LotteryRankShowReward',1,0) as LotteryRankShowReward__count,
if (event_name='LocalPersonalRankReward',1,0) as LocalPersonalRankReward__count,
if (event_name='AllianceAcceptInvite',1,0) as AllianceAcceptInvite__count,
if (event_name='PVEOnHookRewardPreview',1,0) as PVEOnHookRewardPreview__count,
if (event_name='AllianceRewardList', abstract_params(event_params,'len',1) ,null) as AllianceRewardList__len,
if (event_name='PlayerFormationChangeNameSave',1,0) as PlayerFormationChangeNameSave__count,
if (event_name='GetNearBossPoint',1,0) as GetNearBossPoint__count,
if (event_name='PayBeforeCheck',1,0) as PayBeforeCheck__count,
if (event_name='AllianceMilitaryMeritRank',1,0) as AllianceMilitaryMeritRank__count,
if (event_name='RadarCarIntelligenceReceive',1,0) as RadarCarIntelligenceReceive__count,
if (event_name='RadarCarGetInfo',1,0) as RadarCarGetInfo__count,
if (event_name='SyncHeroItemInfo',1,0) as SyncHeroItemInfo__count,
if (event_name='AlSiegeStartTimeCancle',1,0) as AlSiegeStartTimeCancle__count,
if (event_name='AllianceSearchUser',1,0) as AllianceSearchUser__count,
if (event_name='PVEClearanceLineupInfos',1,0) as PVEClearanceLineupInfos__count,
if (event_name='ArenaGetRankList',1,0) as ArenaGetRankList__count,
if (event_name='RandomWhirlSlotReward',1,0) as RandomWhirlSlotReward__count,
if (event_name='MailReward',1,0) as MailReward__count,
if (event_name='AllianceLogMemberView',1,0) as AllianceLogMemberView__count,
if (event_name='UserAllianceDevelopRank',1,0) as UserAllianceDevelopRank__count,
if (event_name='CureSoldier',1,0) as CureSoldier__count,
if (event_name='HeroTrialReward',1,0) as HeroTrialReward__count,
if (event_name='ServerTrendsInfo',1,0) as ServerTrendsInfo__count,
if (event_name='AllianceComment',1,0) as AllianceComment__count,
if (event_name='PreviewBuildingHeroEffectsInfo',1,0) as PreviewBuildingHeroEffectsInfo__count,
if (event_name='UpgradeDirectly', abstract_params(event_params,'goldCost',1) ,null) as UpgradeDirectly__goldCost,
if (event_name='AllianceShowHelp',1,0) as AllianceShowHelp__count,
if (event_name='ReadMail',1,0) as ReadMail__count,
if (event_name='AlSiegeStartTimeSet',1,0) as AlSiegeStartTimeSet__count,
if (event_name='ZoneHonorRank',1,0) as ZoneHonorRank__count,
if (event_name='AllianceSearch',1,0) as AllianceSearch__count,
if (event_name='GarageFormationRepair',1,0) as GarageFormationRepair__count,
if (event_name='DoomsdayBattlepassReceiveAllLevelReward',1,0) as DoomsdayBattlepassReceiveAllLevelReward__count,
if (event_name='PVERankingHandler',1,0) as PVERankingHandler__count,
if (event_name='BattlePassGetReward',1,0) as BattlePassGetReward__count,
if (event_name='SeasonSettlementPackageViewOpen',1,0) as SeasonSettlementPackageViewOpen__count,
if (event_name='AlSiegeWaveWorld',1,0) as AlSiegeWaveWorld__count,
if (event_name='SpeedQueueMultiple',1,0) as SpeedQueueMultiple__count,
if (event_name='EliteNewStrongestRewardReview',1,0) as EliteNewStrongestRewardReview__count,
if (event_name='SerialKillingRankInfo',1,0) as SerialKillingRankInfo__count,
if (event_name='GetAllianceWorldCityInfo',1,0) as GetAllianceWorldCityInfo__count,
if (event_name='PVEClearanceLineupDetailInfo',1,0) as PVEClearanceLineupDetailInfo__count,
if (event_name='UserAllSkinInfo',1,0) as UserAllSkinInfo__count,
if (event_name='AllianceShopUsrBuy', abstract_params(event_params,'num',1) ,null) as AllianceShopUsrBuy__num,
if (event_name='DoomsdayBattlepassReceiveLevelReward',1,0) as DoomsdayBattlepassReceiveLevelReward__count,
if (event_name='DigHeroAdvancePreview',1,0) as DigHeroAdvancePreview__count,
if (event_name='AllianceHelpAll',1,0) as AllianceHelpAll__count,
if (event_name='GetActivityPanelInfo',1,0) as GetActivityPanelInfo__count,
if (event_name='PVECheckpointArmyPreview',1,0) as PVECheckpointArmyPreview__count,
if (event_name='EquipConsumeHandler',1,0) as EquipConsumeHandler__count,
if (event_name='AllianceRewardAllreceive',1,0) as AllianceRewardAllreceive__count,
if (event_name='AllianceShopShow',1,0) as AllianceShopShow__count,
if (event_name='AllianceMemberRank',1,0) as AllianceMemberRank__count,
if (event_name='TradeStationBuy',1,0) as TradeStationBuy__count,
if (event_name='CheckNickName',1,0) as CheckNickName__count,
if (event_name='BindingAccountHandler',1,0) as BindingAccountHandler__count,
if (event_name='AllianceLeave',1,0) as AllianceLeave__count,
if (event_name='AllianceShopAlBuy', abstract_params(event_params,'num',1) ,null) as AllianceShopAlBuy__num,
if (event_name='MarchLFFormation',1,0) as MarchLFFormation__count,
if (event_name='RushModeHandler',1,0) as RushModeHandler__count,
if (event_name='ArenaCalcFormationPower',1,0) as ArenaCalcFormationPower__count,
if (event_name='ReceiveEventTask',1,0) as ReceiveEventTask__count,
if (event_name='RankHandler',1,0) as RankHandler__count,
if (event_name='AllianceShopRecycleShow',1,0) as AllianceShopRecycleShow__count,
if (event_name='AllianceRewardReceive',1,0) as AllianceRewardReceive__count
from `im30-data.im30_bi_ml.lf_mocha` 
where date(event_date)  >= date_sub(current_date(), interval 60 day) 
), 
event_agg_by_day as ( 
select 
universal_user_id,
event_date, 
platform, 
if(sum(login_flag)=0, 0,1) as login_flag, 
if(sum(pay_flag)=0, 0, 1 ) as pay_flag, 
ifnull(sum(case when event_name = 'ArmyMessageHanlder' then ArmyMessageHanlder__count end),0) as ArmyMessageHanlder__count,
ifnull(sum(case when event_name = 'DigGroundClickTipsAfterUpgrade' then DigGroundClickTipsAfterUpgrade__count end),0) as DigGroundClickTipsAfterUpgrade__count,
ifnull(sum(case when event_name = 'ArenaLastRecord' then ArenaLastRecord__count end),0) as ArenaLastRecord__count,
ifnull(sum(case when event_name = 'PVECheckpointBattleStart' then PVECheckpointBattleStart__count end),0) as PVECheckpointBattleStart__count,
ifnull(sum(case when event_name = 'completedRegistration' then completedRegistration__count end),0) as completedRegistration__count,
ifnull(sum(case when event_name = 'AllianceApplyList' then AllianceApplyList__count end),0) as AllianceApplyList__count,
ifnull(sum(case when event_name = 'GarageFormationRepairInfo' then GarageFormationRepairInfo__count end),0) as GarageFormationRepairInfo__count,
ifnull(sum(case when event_name = 'AddComplete' then AddComplete__count end),0) as AddComplete__count,
ifnull(sum(case when event_name = 'DigGroundStationed' then DigGroundStationed__count end),0) as DigGroundStationed__count,
ifnull(sum(case when event_name = 'AlSiegeWaveRecord' then AlSiegeWaveRecord__count end),0) as AlSiegeWaveRecord__count,
ifnull(sum(case when event_name = 'AllianceApplyMsg' then AllianceApplyMsg__count end),0) as AllianceApplyMsg__count,
ifnull(sum(case when event_name = 'MarkMailStatus' then MarkMailStatus__count end),0) as MarkMailStatus__count,
ifnull(sum(case when event_name = 'ScienceResearch' then ScienceResearch__count end),0) as ScienceResearch__count,
ifnull(sum(case when event_name = 'PlayerFormationExtensionSave' then PlayerFormationExtensionSave__count end),0) as PlayerFormationExtensionSave__count,
ifnull(sum(case when event_name = 'ZoneShopRefresh' then ZoneShopRefresh__count end),0) as ZoneShopRefresh__count,
ifnull(sum(case when event_name = 'AllianceLogBattleView' then AllianceLogBattleView__count end),0) as AllianceLogBattleView__count,
ifnull(sum(case when event_name = 'ShowStatusItem' then ShowStatusItem__count end),0) as ShowStatusItem__count,
ifnull(sum(case when event_name = 'PlayerFormationClientInfo' then PlayerFormationClientInfo__count end),0) as PlayerFormationClientInfo__count,
ifnull(sum(case when event_name = 'DigTradeGetUserProperties' then DigTradeGetUserProperties__count end),0) as DigTradeGetUserProperties__count,
ifnull(sum(case when event_name = 'appLaunches' then appLaunches__count end),0) as appLaunches__count,
ifnull(sum(case when event_name = 'PowerRankingHandler' then PowerRankingHandler__count end),0) as PowerRankingHandler__count,
ifnull(sum(case when event_name = 'RegionForceRankingHandler' then RegionForceRankingHandler__count end),0) as RegionForceRankingHandler__count,
ifnull(sum(case when event_name = 'BattlePassGetUserBuyAdvanceExp' then BattlePassGetUserBuyAdvanceExp__count end),0) as BattlePassGetUserBuyAdvanceExp__count,
ifnull(sum(case when event_name = 'LocalPersonalRankInfo' then LocalPersonalRankInfo__count end),0) as LocalPersonalRankInfo__count,
ifnull(sum(case when event_name = 'DigUserRecyclingResource' then DigUserRecyclingResource__count end),0) as DigUserRecyclingResource__count,
ifnull(sum(case when event_name = 'GetNewPlayerInfo' then GetNewPlayerInfo__count end),0) as GetNewPlayerInfo__count,
ifnull(sum(case when event_name = 'GetWorldCityInfo' then GetWorldCityInfo__count end),0) as GetWorldCityInfo__count,
ifnull(sum(case when event_name = 'UserAllianceLevelEffectView' then UserAllianceLevelEffectView__count end),0) as UserAllianceLevelEffectView__count,
ifnull(sum(case when event_name = 'DigFoodCookCancelAndCook' then DigFoodCookCancelAndCook__count end),0) as DigFoodCookCancelAndCook__count,
ifnull(sum(case when event_name = 'BattleEntrance' then BattleEntrance__count end),0) as BattleEntrance__count,
ifnull(sum(case when event_name = 'PersonalGiftClicked' then PersonalGiftClicked__count end),0) as PersonalGiftClicked__count,
ifnull(sum(case when event_name = 'EquipLockHandler' then EquipLockHandler__count end),0) as EquipLockHandler__count,
ifnull(sum(case when event_name = 'AcceptPersonalActivityReward' then AcceptPersonalActivityReward__count end),0) as AcceptPersonalActivityReward__count,
ifnull(sum(case when event_name = 'AllianceDailyTaskView' then AllianceDailyTaskView__count end),0) as AllianceDailyTaskView__count,
ifnull(sum(case when event_name = 'UseItem' then UseItem__num end),0) as UseItem__num,
ifnull(sum(case when event_name = 'DigGroundBuildUplevelGold' then DigGroundBuildUplevelGold__count end),0) as DigGroundBuildUplevelGold__count,
ifnull(sum(case when event_name = 'PlayerFormationSave' then PlayerFormationSave__count end),0) as PlayerFormationSave__count,
ifnull(sum(case when event_name = 'AllianceMilitaryMeritExchangeItems' then AllianceMilitaryMeritExchangeItems__count end),0) as AllianceMilitaryMeritExchangeItems__count,
ifnull(sum(case when event_name = 'DigGroundStationedExp' then DigGroundStationedExp__count end),0) as DigGroundStationedExp__count,
ifnull(sum(case when event_name = 'UserArmsEffectInfo' then UserArmsEffectInfo__count end),0) as UserArmsEffectInfo__count,
ifnull(sum(case when event_name = 'PowerAllianceRankingHandler' then PowerAllianceRankingHandler__count end),0) as PowerAllianceRankingHandler__count,
ifnull(sum(case when event_name = 'ArenaReportDetailInfo' then ArenaReportDetailInfo__count end),0) as ArenaReportDetailInfo__count,
ifnull(sum(case when event_name = 'HonorEditCmd' then HonorEditCmd__count end),0) as HonorEditCmd__count,
ifnull(sum(case when event_name = 'AllianceTransferServerList' then AllianceTransferServerList__count end),0) as AllianceTransferServerList__count,
ifnull(sum(case when event_name = 'MailRewardBatch' then MailRewardBatch__count end),0) as MailRewardBatch__count,
ifnull(sum(case when event_name = 'SerialKillingClaimReward' then SerialKillingClaimReward__count end),0) as SerialKillingClaimReward__count,
ifnull(sum(case when event_name = 'ZoneHonorReward' then ZoneHonorReward__count end),0) as ZoneHonorReward__count,
ifnull(sum(case when event_name = 'AllianceCrossApplyPreview' then AllianceCrossApplyPreview__count end),0) as AllianceCrossApplyPreview__count,
ifnull(sum(case when event_name = 'SetShowQuality' then SetShowQuality__count end),0) as SetShowQuality__count,
ifnull(sum(case when event_name = 'ServerTrendsReward' then ServerTrendsReward__count end),0) as ServerTrendsReward__count,
ifnull(sum(case when event_name = 'AllianceRewardAllRemove' then AllianceRewardAllRemove__count end),0) as AllianceRewardAllRemove__count,
ifnull(sum(case when event_name = 'CureFinish' then CureFinish__count end),0) as CureFinish__count,
ifnull(sum(case when event_name = 'HonorGetInfoCmd' then HonorGetInfoCmd__count end),0) as HonorGetInfoCmd__count,
ifnull(sum(case when event_name = 'AlSiegePanelReward' then AlSiegePanelReward__count end),0) as AlSiegePanelReward__count,
ifnull(sum(case when event_name = 'BoxGiftReward' then BoxGiftReward__count end),0) as BoxGiftReward__count,
ifnull(sum(case when event_name = 'PVEGetInfo' then PVEGetInfo__count end),0) as PVEGetInfo__count,
ifnull(sum(case when event_name = 'UserExpeditionLook' then UserExpeditionLook__count end),0) as UserExpeditionLook__count,
ifnull(sum(case when event_name = 'LotteryHeroCard' then LotteryHeroCard__count end),0) as LotteryHeroCard__count,
ifnull(sum(case when event_name = 'UserExpeditionEffectInfo' then UserExpeditionEffectInfo__count end),0) as UserExpeditionEffectInfo__count,
ifnull(sum(case when event_name = 'EliteNewRefreshData' then EliteNewRefreshData__count end),0) as EliteNewRefreshData__count,
ifnull(sum(case when event_name = 'DigGroundBuildUplevel' then DigGroundBuildUplevel__count end),0) as DigGroundBuildUplevel__count,
ifnull(sum(case when event_name = 'GetRankingBasePanelInfo' then GetRankingBasePanelInfo__count end),0) as GetRankingBasePanelInfo__count,
ifnull(sum(case when event_name = 'UserPayReward' then UserPayReward__count end),0) as UserPayReward__count,
ifnull(sum(case when event_name = 'AllianceMilitaryMeritGet' then AllianceMilitaryMeritGet__count end),0) as AllianceMilitaryMeritGet__count,
ifnull(sum(case when event_name = 'UserAllianceDevelopDonateView' then UserAllianceDevelopDonateView__count end),0) as UserAllianceDevelopDonateView__count,
ifnull(sum(case when event_name = 'DigHeroHandler' then DigHeroHandler__count end),0) as DigHeroHandler__count,
ifnull(sum(case when event_name = 'LFFormationMarchTime' then LFFormationMarchTime__count end),0) as LFFormationMarchTime__count,
ifnull(sum(case when event_name = 'ZoneShopExchange' then ZoneShopExchange__count end),0) as ZoneShopExchange__count,
ifnull(sum(case when event_name = 'ZoneHonorChange' then ZoneHonorChange__count end),0) as ZoneHonorChange__count,
ifnull(sum(case when event_name = 'ZoneShopView' then ZoneShopView__count end),0) as ZoneShopView__count,
ifnull(sum(case when event_name = 'AllianceReinforceList' then AllianceReinforceList__count end),0) as AllianceReinforceList__count,
ifnull(sum(case when event_name = 'AddSoldier' then AddSoldier__count end),0) as AddSoldier__count,
ifnull(sum(case when event_name = 'ArenaRematch' then ArenaRematch__count end),0) as ArenaRematch__count,
ifnull(sum(case when event_name = 'AllianceShopUsrBuyRecord' then AllianceShopUsrBuyRecord__count end),0) as AllianceShopUsrBuyRecord__count,
ifnull(sum(case when event_name = 'SoldierUpgradeComplete' then SoldierUpgradeComplete__count end),0) as SoldierUpgradeComplete__count,
ifnull(sum(case when event_name = 'DigFoodCookCancel' then DigFoodCookCancel__count end),0) as DigFoodCookCancel__count,
ifnull(sum(case when event_name = 'AcceptTaskReward' then AcceptTaskReward__count end),0) as AcceptTaskReward__count,
ifnull(sum(case when event_name = 'DigGroundBuildUplevelNoHeroes' then DigGroundBuildUplevelNoHeroes__count end),0) as DigGroundBuildUplevelNoHeroes__count,
ifnull(sum(case when event_name = 'AllianceCommentView' then AllianceCommentView__count end),0) as AllianceCommentView__count,
ifnull(sum(case when event_name = 'BuildingRankingHandler' then BuildingRankingHandler__count end),0) as BuildingRankingHandler__count,
ifnull(sum(case when event_name = 'GetFoodProduce' then GetFoodProduce__count end),0) as GetFoodProduce__count,
ifnull(sum(case when event_name = 'PVEClearanceReplay' then PVEClearanceReplay__count end),0) as PVEClearanceReplay__count,
ifnull(sum(case when event_name = 'BattlePassGetTaskReward' then BattlePassGetTaskReward__count end),0) as BattlePassGetTaskReward__count,
ifnull(sum(case when event_name = 'DeleteBatch' then DeleteBatch__count end),0) as DeleteBatch__count,
ifnull(sum(case when event_name = 'LotteryHeroCardInfo' then LotteryHeroCardInfo__count end),0) as LotteryHeroCardInfo__count,
ifnull(sum(case when event_name = 'TradeStationGetInfo' then TradeStationGetInfo__count end),0) as TradeStationGetInfo__count,
ifnull(sum(case when event_name = 'UserAllianceLevelGetReward' then UserAllianceLevelGetReward__count end),0) as UserAllianceLevelGetReward__count,
ifnull(sum(case when event_name = 'EliteNewSelfFightList' then EliteNewSelfFightList__count end),0) as EliteNewSelfFightList__count,
ifnull(sum(case when event_name = 'ArenaUserFightRecordNew' then ArenaUserFightRecordNew__count end),0) as ArenaUserFightRecordNew__count,
ifnull(sum(case when event_name = 'UserAlliancePointRank' then UserAlliancePointRank__count end),0) as UserAlliancePointRank__count,
ifnull(sum(case when event_name = 'SerialKillingBuyNum' then SerialKillingBuyNum__count end),0) as SerialKillingBuyNum__count,
ifnull(sum(case when event_name = 'UserExpeditionWard' then UserExpeditionWard__count end),0) as UserExpeditionWard__count,
ifnull(sum(case when event_name = 'ExchangeByActivity' then ExchangeByActivity__num end),0) as ExchangeByActivity__num,
ifnull(sum(case when event_name = 'BattlePassGetDropExpInfo' then BattlePassGetDropExpInfo__count end),0) as BattlePassGetDropExpInfo__count,
ifnull(sum(case when event_name = 'DigHeroLevelUpPreview' then DigHeroLevelUpPreview__count end),0) as DigHeroLevelUpPreview__count,
ifnull(sum(case when event_name = 'HeroQualityActGetReward' then HeroQualityActGetReward__count end),0) as HeroQualityActGetReward__count,
ifnull(sum(case when event_name = 'ArenaGetInfo' then ArenaGetInfo__count end),0) as ArenaGetInfo__count,
ifnull(sum(case when event_name = 'DigFoodCookCmd' then DigFoodCookCmd__number end),0) as DigFoodCookCmd__number,
ifnull(sum(case when event_name = 'UserAllianceDevelopView' then UserAllianceDevelopView__count end),0) as UserAllianceDevelopView__count,
ifnull(sum(case when event_name = 'AlSiegeSetAlarm' then AlSiegeSetAlarm__count end),0) as AlSiegeSetAlarm__count,
ifnull(sum(case when event_name = 'AddArmyImmediately' then AddArmyImmediately__num end),0) as AddArmyImmediately__num,
ifnull(sum(case when event_name = 'EquipUpHandler' then EquipUpHandler__count end),0) as EquipUpHandler__count,
ifnull(sum(case when event_name = 'Pay' then Pay__pay_PriceOfClosingCurrency end),0) as Pay__pay_PriceOfClosingCurrency,
ifnull(sum(case when event_name = 'CrossPersonalRankInfo' then CrossPersonalRankInfo__count end),0) as CrossPersonalRankInfo__count,
ifnull(sum(case when event_name = 'LotteryRankShowReward' then LotteryRankShowReward__count end),0) as LotteryRankShowReward__count,
ifnull(sum(case when event_name = 'LocalPersonalRankReward' then LocalPersonalRankReward__count end),0) as LocalPersonalRankReward__count,
ifnull(sum(case when event_name = 'AllianceAcceptInvite' then AllianceAcceptInvite__count end),0) as AllianceAcceptInvite__count,
ifnull(sum(case when event_name = 'PVEOnHookRewardPreview' then PVEOnHookRewardPreview__count end),0) as PVEOnHookRewardPreview__count,
ifnull(sum(case when event_name = 'AllianceRewardList' then AllianceRewardList__len end),0) as AllianceRewardList__len,
ifnull(sum(case when event_name = 'PlayerFormationChangeNameSave' then PlayerFormationChangeNameSave__count end),0) as PlayerFormationChangeNameSave__count,
ifnull(sum(case when event_name = 'GetNearBossPoint' then GetNearBossPoint__count end),0) as GetNearBossPoint__count,
ifnull(sum(case when event_name = 'PayBeforeCheck' then PayBeforeCheck__count end),0) as PayBeforeCheck__count,
ifnull(sum(case when event_name = 'AllianceMilitaryMeritRank' then AllianceMilitaryMeritRank__count end),0) as AllianceMilitaryMeritRank__count,
ifnull(sum(case when event_name = 'RadarCarIntelligenceReceive' then RadarCarIntelligenceReceive__count end),0) as RadarCarIntelligenceReceive__count,
ifnull(sum(case when event_name = 'RadarCarGetInfo' then RadarCarGetInfo__count end),0) as RadarCarGetInfo__count,
ifnull(sum(case when event_name = 'SyncHeroItemInfo' then SyncHeroItemInfo__count end),0) as SyncHeroItemInfo__count,
ifnull(sum(case when event_name = 'AlSiegeStartTimeCancle' then AlSiegeStartTimeCancle__count end),0) as AlSiegeStartTimeCancle__count,
ifnull(sum(case when event_name = 'AllianceSearchUser' then AllianceSearchUser__count end),0) as AllianceSearchUser__count,
ifnull(sum(case when event_name = 'PVEClearanceLineupInfos' then PVEClearanceLineupInfos__count end),0) as PVEClearanceLineupInfos__count,
ifnull(sum(case when event_name = 'ArenaGetRankList' then ArenaGetRankList__count end),0) as ArenaGetRankList__count,
ifnull(sum(case when event_name = 'RandomWhirlSlotReward' then RandomWhirlSlotReward__count end),0) as RandomWhirlSlotReward__count,
ifnull(sum(case when event_name = 'MailReward' then MailReward__count end),0) as MailReward__count,
ifnull(sum(case when event_name = 'AllianceLogMemberView' then AllianceLogMemberView__count end),0) as AllianceLogMemberView__count,
ifnull(sum(case when event_name = 'UserAllianceDevelopRank' then UserAllianceDevelopRank__count end),0) as UserAllianceDevelopRank__count,
ifnull(sum(case when event_name = 'CureSoldier' then CureSoldier__count end),0) as CureSoldier__count,
ifnull(sum(case when event_name = 'HeroTrialReward' then HeroTrialReward__count end),0) as HeroTrialReward__count,
ifnull(sum(case when event_name = 'ServerTrendsInfo' then ServerTrendsInfo__count end),0) as ServerTrendsInfo__count,
ifnull(sum(case when event_name = 'AllianceComment' then AllianceComment__count end),0) as AllianceComment__count,
ifnull(sum(case when event_name = 'PreviewBuildingHeroEffectsInfo' then PreviewBuildingHeroEffectsInfo__count end),0) as PreviewBuildingHeroEffectsInfo__count,
ifnull(sum(case when event_name = 'UpgradeDirectly' then UpgradeDirectly__goldCost end),0) as UpgradeDirectly__goldCost,
ifnull(sum(case when event_name = 'AllianceShowHelp' then AllianceShowHelp__count end),0) as AllianceShowHelp__count,
ifnull(sum(case when event_name = 'ReadMail' then ReadMail__count end),0) as ReadMail__count,
ifnull(sum(case when event_name = 'AlSiegeStartTimeSet' then AlSiegeStartTimeSet__count end),0) as AlSiegeStartTimeSet__count,
ifnull(sum(case when event_name = 'ZoneHonorRank' then ZoneHonorRank__count end),0) as ZoneHonorRank__count,
ifnull(sum(case when event_name = 'AllianceSearch' then AllianceSearch__count end),0) as AllianceSearch__count,
ifnull(sum(case when event_name = 'GarageFormationRepair' then GarageFormationRepair__count end),0) as GarageFormationRepair__count,
ifnull(sum(case when event_name = 'DoomsdayBattlepassReceiveAllLevelReward' then DoomsdayBattlepassReceiveAllLevelReward__count end),0) as DoomsdayBattlepassReceiveAllLevelReward__count,
ifnull(sum(case when event_name = 'PVERankingHandler' then PVERankingHandler__count end),0) as PVERankingHandler__count,
ifnull(sum(case when event_name = 'BattlePassGetReward' then BattlePassGetReward__count end),0) as BattlePassGetReward__count,
ifnull(sum(case when event_name = 'SeasonSettlementPackageViewOpen' then SeasonSettlementPackageViewOpen__count end),0) as SeasonSettlementPackageViewOpen__count,
ifnull(sum(case when event_name = 'AlSiegeWaveWorld' then AlSiegeWaveWorld__count end),0) as AlSiegeWaveWorld__count,
ifnull(sum(case when event_name = 'SpeedQueueMultiple' then SpeedQueueMultiple__count end),0) as SpeedQueueMultiple__count,
ifnull(sum(case when event_name = 'EliteNewStrongestRewardReview' then EliteNewStrongestRewardReview__count end),0) as EliteNewStrongestRewardReview__count,
ifnull(sum(case when event_name = 'SerialKillingRankInfo' then SerialKillingRankInfo__count end),0) as SerialKillingRankInfo__count,
ifnull(sum(case when event_name = 'GetAllianceWorldCityInfo' then GetAllianceWorldCityInfo__count end),0) as GetAllianceWorldCityInfo__count,
ifnull(sum(case when event_name = 'PVEClearanceLineupDetailInfo' then PVEClearanceLineupDetailInfo__count end),0) as PVEClearanceLineupDetailInfo__count,
ifnull(sum(case when event_name = 'UserAllSkinInfo' then UserAllSkinInfo__count end),0) as UserAllSkinInfo__count,
ifnull(sum(case when event_name = 'AllianceShopUsrBuy' then AllianceShopUsrBuy__num end),0) as AllianceShopUsrBuy__num,
ifnull(sum(case when event_name = 'DoomsdayBattlepassReceiveLevelReward' then DoomsdayBattlepassReceiveLevelReward__count end),0) as DoomsdayBattlepassReceiveLevelReward__count,
ifnull(sum(case when event_name = 'DigHeroAdvancePreview' then DigHeroAdvancePreview__count end),0) as DigHeroAdvancePreview__count,
ifnull(sum(case when event_name = 'AllianceHelpAll' then AllianceHelpAll__count end),0) as AllianceHelpAll__count,
ifnull(sum(case when event_name = 'GetActivityPanelInfo' then GetActivityPanelInfo__count end),0) as GetActivityPanelInfo__count,
ifnull(sum(case when event_name = 'PVECheckpointArmyPreview' then PVECheckpointArmyPreview__count end),0) as PVECheckpointArmyPreview__count,
ifnull(sum(case when event_name = 'EquipConsumeHandler' then EquipConsumeHandler__count end),0) as EquipConsumeHandler__count,
ifnull(sum(case when event_name = 'AllianceRewardAllreceive' then AllianceRewardAllreceive__count end),0) as AllianceRewardAllreceive__count,
ifnull(sum(case when event_name = 'AllianceShopShow' then AllianceShopShow__count end),0) as AllianceShopShow__count,
ifnull(sum(case when event_name = 'AllianceMemberRank' then AllianceMemberRank__count end),0) as AllianceMemberRank__count,
ifnull(sum(case when event_name = 'TradeStationBuy' then TradeStationBuy__count end),0) as TradeStationBuy__count,
ifnull(sum(case when event_name = 'CheckNickName' then CheckNickName__count end),0) as CheckNickName__count,
ifnull(sum(case when event_name = 'BindingAccountHandler' then BindingAccountHandler__count end),0) as BindingAccountHandler__count,
ifnull(sum(case when event_name = 'AllianceLeave' then AllianceLeave__count end),0) as AllianceLeave__count,
ifnull(sum(case when event_name = 'AllianceShopAlBuy' then AllianceShopAlBuy__num end),0) as AllianceShopAlBuy__num,
ifnull(sum(case when event_name = 'MarchLFFormation' then MarchLFFormation__count end),0) as MarchLFFormation__count,
ifnull(sum(case when event_name = 'RushModeHandler' then RushModeHandler__count end),0) as RushModeHandler__count,
ifnull(sum(case when event_name = 'ArenaCalcFormationPower' then ArenaCalcFormationPower__count end),0) as ArenaCalcFormationPower__count,
ifnull(sum(case when event_name = 'ReceiveEventTask' then ReceiveEventTask__count end),0) as ReceiveEventTask__count,
ifnull(sum(case when event_name = 'RankHandler' then RankHandler__count end),0) as RankHandler__count,
ifnull(sum(case when event_name = 'AllianceShopRecycleShow' then AllianceShopRecycleShow__count end),0) as AllianceShopRecycleShow__count,
ifnull(sum(case when event_name = 'AllianceRewardReceive' then AllianceRewardReceive__count end),0) as AllianceRewardReceive__count
from data_flat_1
group by universal_user_id, event_date,platform 
) 
select 
a.*, 
ifnull(b.login_flag,0) as login_flag, 
ifnull(b.pay_flag,0) as pay_flag, 
 ifnull(b.ArmyMessageHanlder__count,0) as ArmyMessageHanlder__count,
ifnull(b.DigGroundClickTipsAfterUpgrade__count,0) as DigGroundClickTipsAfterUpgrade__count,
ifnull(b.ArenaLastRecord__count,0) as ArenaLastRecord__count,
ifnull(b.PVECheckpointBattleStart__count,0) as PVECheckpointBattleStart__count,
ifnull(b.completedRegistration__count,0) as completedRegistration__count,
ifnull(b.AllianceApplyList__count,0) as AllianceApplyList__count,
ifnull(b.GarageFormationRepairInfo__count,0) as GarageFormationRepairInfo__count,
ifnull(b.AddComplete__count,0) as AddComplete__count,
ifnull(b.DigGroundStationed__count,0) as DigGroundStationed__count,
ifnull(b.AlSiegeWaveRecord__count,0) as AlSiegeWaveRecord__count,
ifnull(b.AllianceApplyMsg__count,0) as AllianceApplyMsg__count,
ifnull(b.MarkMailStatus__count,0) as MarkMailStatus__count,
ifnull(b.ScienceResearch__count,0) as ScienceResearch__count,
ifnull(b.PlayerFormationExtensionSave__count,0) as PlayerFormationExtensionSave__count,
ifnull(b.ZoneShopRefresh__count,0) as ZoneShopRefresh__count,
ifnull(b.AllianceLogBattleView__count,0) as AllianceLogBattleView__count,
ifnull(b.ShowStatusItem__count,0) as ShowStatusItem__count,
ifnull(b.PlayerFormationClientInfo__count,0) as PlayerFormationClientInfo__count,
ifnull(b.DigTradeGetUserProperties__count,0) as DigTradeGetUserProperties__count,
ifnull(b.appLaunches__count,0) as appLaunches__count,
ifnull(b.PowerRankingHandler__count,0) as PowerRankingHandler__count,
ifnull(b.RegionForceRankingHandler__count,0) as RegionForceRankingHandler__count,
ifnull(b.BattlePassGetUserBuyAdvanceExp__count,0) as BattlePassGetUserBuyAdvanceExp__count,
ifnull(b.LocalPersonalRankInfo__count,0) as LocalPersonalRankInfo__count,
ifnull(b.DigUserRecyclingResource__count,0) as DigUserRecyclingResource__count,
ifnull(b.GetNewPlayerInfo__count,0) as GetNewPlayerInfo__count,
ifnull(b.GetWorldCityInfo__count,0) as GetWorldCityInfo__count,
ifnull(b.UserAllianceLevelEffectView__count,0) as UserAllianceLevelEffectView__count,
ifnull(b.DigFoodCookCancelAndCook__count,0) as DigFoodCookCancelAndCook__count,
ifnull(b.BattleEntrance__count,0) as BattleEntrance__count,
ifnull(b.PersonalGiftClicked__count,0) as PersonalGiftClicked__count,
ifnull(b.EquipLockHandler__count,0) as EquipLockHandler__count,
ifnull(b.AcceptPersonalActivityReward__count,0) as AcceptPersonalActivityReward__count,
ifnull(b.AllianceDailyTaskView__count,0) as AllianceDailyTaskView__count,
ifnull(b.UseItem__num,0) as UseItem__num,
ifnull(b.DigGroundBuildUplevelGold__count,0) as DigGroundBuildUplevelGold__count,
ifnull(b.PlayerFormationSave__count,0) as PlayerFormationSave__count,
ifnull(b.AllianceMilitaryMeritExchangeItems__count,0) as AllianceMilitaryMeritExchangeItems__count,
ifnull(b.DigGroundStationedExp__count,0) as DigGroundStationedExp__count,
ifnull(b.UserArmsEffectInfo__count,0) as UserArmsEffectInfo__count,
ifnull(b.PowerAllianceRankingHandler__count,0) as PowerAllianceRankingHandler__count,
ifnull(b.ArenaReportDetailInfo__count,0) as ArenaReportDetailInfo__count,
ifnull(b.HonorEditCmd__count,0) as HonorEditCmd__count,
ifnull(b.AllianceTransferServerList__count,0) as AllianceTransferServerList__count,
ifnull(b.MailRewardBatch__count,0) as MailRewardBatch__count,
ifnull(b.SerialKillingClaimReward__count,0) as SerialKillingClaimReward__count,
ifnull(b.ZoneHonorReward__count,0) as ZoneHonorReward__count,
ifnull(b.AllianceCrossApplyPreview__count,0) as AllianceCrossApplyPreview__count,
ifnull(b.SetShowQuality__count,0) as SetShowQuality__count,
ifnull(b.ServerTrendsReward__count,0) as ServerTrendsReward__count,
ifnull(b.AllianceRewardAllRemove__count,0) as AllianceRewardAllRemove__count,
ifnull(b.CureFinish__count,0) as CureFinish__count,
ifnull(b.HonorGetInfoCmd__count,0) as HonorGetInfoCmd__count,
ifnull(b.AlSiegePanelReward__count,0) as AlSiegePanelReward__count,
ifnull(b.BoxGiftReward__count,0) as BoxGiftReward__count,
ifnull(b.PVEGetInfo__count,0) as PVEGetInfo__count,
ifnull(b.UserExpeditionLook__count,0) as UserExpeditionLook__count,
ifnull(b.LotteryHeroCard__count,0) as LotteryHeroCard__count,
ifnull(b.UserExpeditionEffectInfo__count,0) as UserExpeditionEffectInfo__count,
ifnull(b.EliteNewRefreshData__count,0) as EliteNewRefreshData__count,
ifnull(b.DigGroundBuildUplevel__count,0) as DigGroundBuildUplevel__count,
ifnull(b.GetRankingBasePanelInfo__count,0) as GetRankingBasePanelInfo__count,
ifnull(b.UserPayReward__count,0) as UserPayReward__count,
ifnull(b.AllianceMilitaryMeritGet__count,0) as AllianceMilitaryMeritGet__count,
ifnull(b.UserAllianceDevelopDonateView__count,0) as UserAllianceDevelopDonateView__count,
ifnull(b.DigHeroHandler__count,0) as DigHeroHandler__count,
ifnull(b.LFFormationMarchTime__count,0) as LFFormationMarchTime__count,
ifnull(b.ZoneShopExchange__count,0) as ZoneShopExchange__count,
ifnull(b.ZoneHonorChange__count,0) as ZoneHonorChange__count,
ifnull(b.ZoneShopView__count,0) as ZoneShopView__count,
ifnull(b.AllianceReinforceList__count,0) as AllianceReinforceList__count,
ifnull(b.AddSoldier__count,0) as AddSoldier__count,
ifnull(b.ArenaRematch__count,0) as ArenaRematch__count,
ifnull(b.AllianceShopUsrBuyRecord__count,0) as AllianceShopUsrBuyRecord__count,
ifnull(b.SoldierUpgradeComplete__count,0) as SoldierUpgradeComplete__count,
ifnull(b.DigFoodCookCancel__count,0) as DigFoodCookCancel__count,
ifnull(b.AcceptTaskReward__count,0) as AcceptTaskReward__count,
ifnull(b.DigGroundBuildUplevelNoHeroes__count,0) as DigGroundBuildUplevelNoHeroes__count,
ifnull(b.AllianceCommentView__count,0) as AllianceCommentView__count,
ifnull(b.BuildingRankingHandler__count,0) as BuildingRankingHandler__count,
ifnull(b.GetFoodProduce__count,0) as GetFoodProduce__count,
ifnull(b.PVEClearanceReplay__count,0) as PVEClearanceReplay__count,
ifnull(b.BattlePassGetTaskReward__count,0) as BattlePassGetTaskReward__count,
ifnull(b.DeleteBatch__count,0) as DeleteBatch__count,
ifnull(b.LotteryHeroCardInfo__count,0) as LotteryHeroCardInfo__count,
ifnull(b.TradeStationGetInfo__count,0) as TradeStationGetInfo__count,
ifnull(b.UserAllianceLevelGetReward__count,0) as UserAllianceLevelGetReward__count,
ifnull(b.EliteNewSelfFightList__count,0) as EliteNewSelfFightList__count,
ifnull(b.ArenaUserFightRecordNew__count,0) as ArenaUserFightRecordNew__count,
ifnull(b.UserAlliancePointRank__count,0) as UserAlliancePointRank__count,
ifnull(b.SerialKillingBuyNum__count,0) as SerialKillingBuyNum__count,
ifnull(b.UserExpeditionWard__count,0) as UserExpeditionWard__count,
ifnull(b.ExchangeByActivity__num,0) as ExchangeByActivity__num,
ifnull(b.BattlePassGetDropExpInfo__count,0) as BattlePassGetDropExpInfo__count,
ifnull(b.DigHeroLevelUpPreview__count,0) as DigHeroLevelUpPreview__count,
ifnull(b.HeroQualityActGetReward__count,0) as HeroQualityActGetReward__count,
ifnull(b.ArenaGetInfo__count,0) as ArenaGetInfo__count,
ifnull(b.DigFoodCookCmd__number,0) as DigFoodCookCmd__number,
ifnull(b.UserAllianceDevelopView__count,0) as UserAllianceDevelopView__count,
ifnull(b.AlSiegeSetAlarm__count,0) as AlSiegeSetAlarm__count,
ifnull(b.AddArmyImmediately__num,0) as AddArmyImmediately__num,
ifnull(b.EquipUpHandler__count,0) as EquipUpHandler__count,
ifnull(b.Pay__pay_PriceOfClosingCurrency,0) as Pay__pay_PriceOfClosingCurrency,
ifnull(b.CrossPersonalRankInfo__count,0) as CrossPersonalRankInfo__count,
ifnull(b.LotteryRankShowReward__count,0) as LotteryRankShowReward__count,
ifnull(b.LocalPersonalRankReward__count,0) as LocalPersonalRankReward__count,
ifnull(b.AllianceAcceptInvite__count,0) as AllianceAcceptInvite__count,
ifnull(b.PVEOnHookRewardPreview__count,0) as PVEOnHookRewardPreview__count,
ifnull(b.AllianceRewardList__len,0) as AllianceRewardList__len,
ifnull(b.PlayerFormationChangeNameSave__count,0) as PlayerFormationChangeNameSave__count,
ifnull(b.GetNearBossPoint__count,0) as GetNearBossPoint__count,
ifnull(b.PayBeforeCheck__count,0) as PayBeforeCheck__count,
ifnull(b.AllianceMilitaryMeritRank__count,0) as AllianceMilitaryMeritRank__count,
ifnull(b.RadarCarIntelligenceReceive__count,0) as RadarCarIntelligenceReceive__count,
ifnull(b.RadarCarGetInfo__count,0) as RadarCarGetInfo__count,
ifnull(b.SyncHeroItemInfo__count,0) as SyncHeroItemInfo__count,
ifnull(b.AlSiegeStartTimeCancle__count,0) as AlSiegeStartTimeCancle__count,
ifnull(b.AllianceSearchUser__count,0) as AllianceSearchUser__count,
ifnull(b.PVEClearanceLineupInfos__count,0) as PVEClearanceLineupInfos__count,
ifnull(b.ArenaGetRankList__count,0) as ArenaGetRankList__count,
ifnull(b.RandomWhirlSlotReward__count,0) as RandomWhirlSlotReward__count,
ifnull(b.MailReward__count,0) as MailReward__count,
ifnull(b.AllianceLogMemberView__count,0) as AllianceLogMemberView__count,
ifnull(b.UserAllianceDevelopRank__count,0) as UserAllianceDevelopRank__count,
ifnull(b.CureSoldier__count,0) as CureSoldier__count,
ifnull(b.HeroTrialReward__count,0) as HeroTrialReward__count,
ifnull(b.ServerTrendsInfo__count,0) as ServerTrendsInfo__count,
ifnull(b.AllianceComment__count,0) as AllianceComment__count,
ifnull(b.PreviewBuildingHeroEffectsInfo__count,0) as PreviewBuildingHeroEffectsInfo__count,
ifnull(b.UpgradeDirectly__goldCost,0) as UpgradeDirectly__goldCost,
ifnull(b.AllianceShowHelp__count,0) as AllianceShowHelp__count,
ifnull(b.ReadMail__count,0) as ReadMail__count,
ifnull(b.AlSiegeStartTimeSet__count,0) as AlSiegeStartTimeSet__count,
ifnull(b.ZoneHonorRank__count,0) as ZoneHonorRank__count,
ifnull(b.AllianceSearch__count,0) as AllianceSearch__count,
ifnull(b.GarageFormationRepair__count,0) as GarageFormationRepair__count,
ifnull(b.DoomsdayBattlepassReceiveAllLevelReward__count,0) as DoomsdayBattlepassReceiveAllLevelReward__count,
ifnull(b.PVERankingHandler__count,0) as PVERankingHandler__count,
ifnull(b.BattlePassGetReward__count,0) as BattlePassGetReward__count,
ifnull(b.SeasonSettlementPackageViewOpen__count,0) as SeasonSettlementPackageViewOpen__count,
ifnull(b.AlSiegeWaveWorld__count,0) as AlSiegeWaveWorld__count,
ifnull(b.SpeedQueueMultiple__count,0) as SpeedQueueMultiple__count,
ifnull(b.EliteNewStrongestRewardReview__count,0) as EliteNewStrongestRewardReview__count,
ifnull(b.SerialKillingRankInfo__count,0) as SerialKillingRankInfo__count,
ifnull(b.GetAllianceWorldCityInfo__count,0) as GetAllianceWorldCityInfo__count,
ifnull(b.PVEClearanceLineupDetailInfo__count,0) as PVEClearanceLineupDetailInfo__count,
ifnull(b.UserAllSkinInfo__count,0) as UserAllSkinInfo__count,
ifnull(b.AllianceShopUsrBuy__num,0) as AllianceShopUsrBuy__num,
ifnull(b.DoomsdayBattlepassReceiveLevelReward__count,0) as DoomsdayBattlepassReceiveLevelReward__count,
ifnull(b.DigHeroAdvancePreview__count,0) as DigHeroAdvancePreview__count,
ifnull(b.AllianceHelpAll__count,0) as AllianceHelpAll__count,
ifnull(b.GetActivityPanelInfo__count,0) as GetActivityPanelInfo__count,
ifnull(b.PVECheckpointArmyPreview__count,0) as PVECheckpointArmyPreview__count,
ifnull(b.EquipConsumeHandler__count,0) as EquipConsumeHandler__count,
ifnull(b.AllianceRewardAllreceive__count,0) as AllianceRewardAllreceive__count,
ifnull(b.AllianceShopShow__count,0) as AllianceShopShow__count,
ifnull(b.AllianceMemberRank__count,0) as AllianceMemberRank__count,
ifnull(b.TradeStationBuy__count,0) as TradeStationBuy__count,
ifnull(b.CheckNickName__count,0) as CheckNickName__count,
ifnull(b.BindingAccountHandler__count,0) as BindingAccountHandler__count,
ifnull(b.AllianceLeave__count,0) as AllianceLeave__count,
ifnull(b.AllianceShopAlBuy__num,0) as AllianceShopAlBuy__num,
ifnull(b.MarchLFFormation__count,0) as MarchLFFormation__count,
ifnull(b.RushModeHandler__count,0) as RushModeHandler__count,
ifnull(b.ArenaCalcFormationPower__count,0) as ArenaCalcFormationPower__count,
ifnull(b.ReceiveEventTask__count,0) as ReceiveEventTask__count,
ifnull(b.RankHandler__count,0) as RankHandler__count,
ifnull(b.AllianceShopRecycleShow__count,0) as AllianceShopRecycleShow__count,
ifnull(b.AllianceRewardReceive__count,0) as AllianceRewardReceive__count,
current_timestamp() as collect_time 
from full_user_date a 
left join event_agg_by_day b 
on a.universal_user_id=b.universal_user_id
and a.event_date=b.event_date 
and upper(a.platform)=upper(b.platform) 
